#import "../lib.typ": *
#import "@preview/cetz:0.4.2"

= Dictionary Coding I: LZ77 and LZ78

#epigraph[
  "The definition of insanity is doing the same thing over and over again and
  expecting different results. A data compressor, on the other hand, sees you
  doing the same thing over and over again and quietly replaces it with a pointer."
][_Attributed to no one, but felt by every compression engineer_]

Imagine you are copying a book by hand. On page 47 you encounter the phrase
_"the quick brown fox"_ for the first time, and you write it out letter by letter.
Then, on page 53, the exact same phrase appears again. A smart copyist would not
laboriously write out all eighteen characters; they would simply jot a margin
note: _"same as page 47, line 12."_ That two-word note takes far less ink than
the original phrase. This, in essence, is *dictionary coding*: instead of
re-emitting text you have already seen, emit a short *reference* to the earlier
occurrence.

The entropy coders we built in Chapters 24 through 27 (Huffman, arithmetic
coding, rANS) are brilliant, but they are amnesiac. They see each symbol in
isolation and price it by its marginal frequency. They have no memory of
*patterns*. Feed them the string `abcabcabcabc` and they see twelve symbols,
each cheap (one of two letters). They cannot see that the whole thing is just
`abc` repeated four times. Dictionary coding sees exactly that, and says: emit
`abc` once, then "copy the last 3 bytes, four more times."

This one idea (reference the past instead of repeating it) is the theoretical
and practical backbone of almost every general-purpose compressor in widespread
use: gzip, zlib, PNG, ZIP, Zstandard, 7-Zip, Brotli, and many more. And it all
traces back to two researchers at the Technion, Israel's leading technical
university, who published a pair of landmark papers in 1977 and 1978.

#recap[
  In *Chapter 24* we built Huffman coding, the optimal *symbol-by-symbol*
  prefix code. In *Chapter 26* arithmetic coding, and in *Chapter 27* rANS,
  two ways to approach the entropy limit. All of those coders model individual
  symbols. This chapter starts Part II of Volume II: instead of modeling
  symbols, we model *substrings*. In *Chapter 30* we will combine what we build
  here with Huffman coding to produce DEFLATE, the engine of gzip and the web.
]

#objectives((
  "Explain the sliding-window intuition of LZ77 and trace a worked encoding by hand.",
  "Explain the explicit-dictionary intuition of LZ78 and contrast it with LZ77.",
  "State and intuitively understand the universality result: why both algorithms converge to the entropy rate.",
  "Understand LZSS, the practical improvement that made LZ77 deployable.",
  "Implement Step 12 of tinyzip: a working LZ77 match-finder, greedy parser, and token stream in Python 3.14.",
  "Read the algorithm profiles for LZ77, LZ78, and LZSS and understand the trade-offs.",
))

== The Problem with Entropy Coding Alone

Let us be precise about what entropy coding cannot do.

Take the string:
#align(center)[`abracadabra`]

The frequencies are: a×5, b×2, r×2, c×1, d×1, eleven symbols total.
Shannon entropy $H ≈ 2.04$ bits per symbol, so the entropy limit for this
string is about $11 × 2.04 ≈ 22.5$ bits. A Huffman coder, working
symbol-by-symbol, can get close to that.

But here is the thing: the string has *far* more structure than raw symbol
frequencies reveal. The substrings `abra` and `bra` repeat. The string was
almost certainly generated by some rule, not eleven independent coin-flips. An
ideal compressor should be able to say: "emit `abr`, then `a`, then `cad`,
then 'copy the first 4 characters', then `a`." That reference-based description
is much shorter.

This is the gap between *first-order entropy* (which measures single-symbol
surprise) and *higher-order entropy* (which measures surprise given context).
Dictionary coding closes this gap by making back-references explicit.

#keyidea[
  Entropy coding and dictionary coding are *complementary*, not competing.
  Dictionary coding removes long-range repetitions; entropy coding then removes
  the remaining symbol-by-symbol redundancy. DEFLATE (Chapter 30) stacks them
  in exactly this order.
]

== LZ77: The Sliding-Window Approach (1977)

*Abraham Lempel* and *Jacob Ziv* published "A Universal Algorithm for Sequential
Data Compression" in the May 1977 issue of _IEEE Transactions on Information
Theory_. It is among the most cited papers in computer science.

=== The Three Parts: Search Buffer, Lookahead Buffer, and Tokens

LZ77 divides the input into two imaginary windows:

- *Search buffer* (also called the *history buffer* or *sliding window*): the
  $W$ bytes most recently *encoded*. This is the "dictionary."
- *Lookahead buffer*: the next $L$ bytes waiting to be encoded.

At each step the encoder asks: _does the current lookahead appear anywhere in
the search buffer?_ If yes, it emits a compact *back-reference* token
$(d, ell, c)$ where:

- $d$ is the *distance* (how many bytes back the match starts),
- $ell$ is the *length* (how many bytes the match covers),
- $c$ is the *next literal*, the character right after the match.

If no match is found, it emits a literal token $(0, 0, c)$.

After emitting a token, both windows slide forward: the matched bytes (plus the
literal) move from the lookahead into the search buffer.

#aside[
  The original Lempel–Ziv 1977 paper defines tokens as *(offset, length, literal)*
  triples. In practice, almost every implementation uses some variant of this
  encoding; the exact bit layout varies. DEFLATE, for instance, separates
  literals from (length, distance) pairs and encodes them with Huffman codes.
]

=== A Worked Example

Let us compress `abracadabra` step by step with a search buffer of size 8 and
a lookahead of size 4.

We will write the search buffer content in square brackets and the lookahead
in angle brackets.

```
Position 0:  [] <abra>
  No match (empty buffer). Emit (0, 0, 'a'). Slide 1.
Position 1:  [a] <brac>
  Look for 'b' in [a] - no match. Emit (0, 0, 'b'). Slide 1.
Position 2:  [ab] <raca>
  Look for 'r' in [ab] - no match. Emit (0, 0, 'r'). Slide 1.
Position 3:  [abr] <acad>
  Look for 'a' in [abr] - match at distance 3, length 1.
  Lookahead next char after match: 'c'. Emit (3, 1, 'c'). Slide 2.
Position 5:  [abrac] <adab>
  'a' found at distance 5 (the first 'a'), length 1.
  Next char: 'd'. Emit (5, 1, 'd'). Slide 2.
Position 7:  [abracad] <abra>
  'a' at distance 7, but can we match longer?
  'ab' at distance 7 → check: buffer[-7..] = 'a', buffer[-6..] = 'b'. Yes!
  'abr' → yes. 'abra' → yes, length 4.
  After length-4 match the lookahead is exhausted. Emit (7, 4, '').
  (End of input.)
```

So the encoded token stream is:
```
(0,0,'a')  (0,0,'b')  (0,0,'r')  (3,1,'c')  (5,1,'d')  (7,4,'')
```

Six tokens cover eleven bytes. The first three are literals; the last three are
back-references. Notice how `(7, 4, '')` compactly expresses "copy the first
four bytes of what we already sent." That is the power of sliding-window
compression.

#note[
  This trace is *classic* LZ77, which happily emits even length-1 matches like
  `(3, 1, 'c')`. As we will see in the LZSS section below, a length-1 or length-2
  "match" actually costs *more* than just spelling the byte out, so the practical
  code we build in Step 12 sets a `MIN_MATCH` of 3 and emits those short
  would-be-matches as plain literals instead. On `abracadabra` that leaves a
  single real back-reference (the final length-4 `abra`), which is exactly what
  the `lz77.py` self-test reports.
]

=== Decoding Is Trivial

Decoding LZ77 is remarkably simple: maintain a buffer of the decoded bytes so
far. For each token $(d, ell, c)$:
1. Go back $d$ positions in the decoded buffer.
2. Copy $ell$ bytes from there to the output.
3. Append the literal $c$.

There is one subtlety called an *overlap match* or *run-length copy*: if
$ell > d$, the copy extends into the region it is writing. For example, with
$d=2$ and $ell=6$: copy bytes at positions $[-2], [-1], [-2], [-1], [-2], [-1]$
This produces a pattern that repeats the two preceding bytes, effectively
run-length encoding. Decoders must handle this by copying one byte at a time,
not with a `memcpy`.

#pitfall[
  Overlap copies look like a bug but are a feature. They let LZ77 represent
  run-length patterns (like `aaaaaaa`) without a separate RLE step. But a
  decoder that uses `memcpy` for back-references *will produce wrong output* on
  overlapping matches. Always copy one byte at a time, or use `memmove`.
]

=== Why LZ77 Is Universal

Lempel and Ziv proved something remarkable: as the window size $W$ grows
without bound and the input length $n$ grows, the compression ratio of LZ77
converges to the *entropy rate* of any stationary ergodic source. The algorithm does this *without knowing the source statistics in advance*. This is
called *universal compression*.

#gomaths("Entropy rate and universal compression")[
  In Chapters 18–19 we defined the entropy $H(X)$ of a single random variable.
  For a *sequence* of symbols $X_1, X_2, X_3, dots$ that are not independent
  but are *stationary* (the joint distribution does not shift with time), the
  *entropy rate* is:
  $ h = lim_(n -> oo) (H(X_1, X_2, dots, X_n)) / n $
  This is the minimum bits-per-symbol any lossless coder can achieve on that
  source, no matter how good the model. LZ77 achieves $h$ asymptotically *without
  ever estimating probabilities*: the sliding window implicitly does the modeling
  by finding long repeated phrases.

  *Intuition:* if a phrase of length $k$ has appeared before, its re-occurrence
  is not surprising. By referring back to it with a short pointer, you are
  effectively saying "this phrase has high probability," without ever computing
  a probability.
]

The universality proof uses a clever counting argument: the number of distinct
phrases LZ77 produces on a length-$n$ input grows roughly as $n \/ log n$.
Each phrase can be encoded in $log_2 W$ bits (the distance) plus a small
length field. As $n -> oo$, this converges to $h$ bits per symbol.

In practice, with realistic window sizes (32 KB for DEFLATE, 512 KB–8 MB for
LZMA), LZ77 variants are already extraordinarily effective on real data.

#algo(
  name: "LZ77",
  year: "1977",
  authors: "Abraham Lempel, Jacob Ziv (Technion, Israel)",
  aim: "Universal lossless compression via back-references into a sliding history window.",
  complexity: "Naïve: O(W·n) encode; O(n) decode. With suffix trees/hash chains: O(n) average encode.",
  strengths: "Universal (converges to entropy rate); simple decoder; adapts automatically to data; no model training needed.",
  weaknesses: "Naïve match-finding is slow; small windows limit ratio; literals waste space when matches are short.",
  superseded: "LZSS (shorter tokens), DEFLATE (adds Huffman coding), LZMA (adds range coding + longer window).",
)[]

== LZ78: The Explicit-Dictionary Approach (1978)

One year after LZ77, Lempel and Ziv published a second scheme in the September
1978 _IEEE Transactions on Information Theory_: "Compression of Individual
Sequences via Variable-Rate Coding." We now call it *LZ78* or *LZ2*.

The intuition is different. Instead of looking backward in a window, LZ78 builds
an explicit, numbered *phrase dictionary* that grows as encoding proceeds. Each
token is *(index, symbol)*: "use phrase \#index from the dictionary and append
this symbol." The new phrase (index's expansion + symbol) is then added to the
dictionary.

=== LZ78 Step by Step

Let us trace `abracadabra` again.

```
Dictionary:  {} (empty)
Token stream: []

Step 1: Lookahead = 'a'. No prefix in dictionary. Emit (0,'a'). Add "a"→1.
Step 2: Lookahead = 'b'. No prefix. Emit (0,'b'). Add "b"→2.
Step 3: Lookahead = 'r'. No prefix. Emit (0,'r'). Add "r"→3.
Step 4: Lookahead = 'a'. "a" is in dictionary (entry 1). Try to extend:
        next = 'c'. "ac" not in dictionary. Emit (1,'c'). Add "ac"→4.
Step 5: Lookahead = 'a'. "a"→1. Next = 'd'. "ad" not in dict. Emit (1,'d'). Add "ad"→5.
Step 6: Lookahead = 'a'. "a"→1. Next = 'b'. "ab" not in dict. Emit (1,'b'). Add "ab"→6.
Step 7: Lookahead = 'r'. "r"→3. Next = 'a'. "ra" not in dict. Emit (3,'a'). Add "ra"→7.
(Input exhausted.)
```

Tokens: `(0,'a')(0,'b')(0,'r')(1,'c')(1,'d')(1,'b')(3,'a')`, 7 tokens for 11 characters. On a longer text, dictionary entries grow longer and fewer tokens are needed per character.

Decoding is equally simple: maintain a dictionary; for each token $(i, c)$,
output dictionary[i] concatenated with $c$, then add that phrase to the
dictionary.

#algo(
  name: "LZ78",
  year: "1978",
  authors: "Abraham Lempel, Jacob Ziv (Technion, Israel)",
  aim: "Universal compression via an explicitly maintained, growing phrase dictionary.",
  complexity: "O(n) expected with hash table. Dictionary can grow unboundedly; may need pruning.",
  strengths: "Universal; explicit dictionary enables direct lookup (no window scan); elegant theory.",
  weaknesses: "Dictionary can grow very large; no bound on memory; harder to implement pruning without losing correctness.",
  superseded: "LZW (drops the literal from each token); LZMA, LZX (better ratio); Zstandard (trained dictionaries).",
)[]

=== LZ77 vs LZ78: The Key Differences

Both algorithms are universal. Their practical differences drive the fork in
the family tree:

#align(center, table(
  columns: (auto, 1fr, 1fr),
  [*Property*], [*LZ77*], [*LZ78*],
  [Dictionary], [Implicit: sliding window of recent bytes], [Explicit: numbered phrase table],
  [Memory], [Fixed (window size)], [Grows without bound],
  [Match search], [Scan backward in window], [Hash table lookup],
  [Token], [(distance, length, literal)], [(index, symbol)],
  [Decoding], [O(1) per byte with a ring buffer], [O(1) per token with table lookup],
  [Practical descendants], [LZSS, DEFLATE, LZMA, zstd, LZ4], [LZW (GIF, ZIP), LZMW, LZJ],
))

== LZSS: Making LZ77 Practical

The original LZ77 paper emits *(distance, length, literal)* triples even for
literal characters, which wastes space: a single-character "match" of length 0
is encoded as a triple that costs more than the character itself.

In 1982 James Storer and Thomas Szymanski published an improvement, now called
*LZSS* (Lempel–Ziv–Storer–Szymanski). The key change: add a *flag bit* before
each token.

- Flag = 0 → the next token is a raw literal byte.
- Flag = 1 → the next token is a (distance, length) back-reference pair.

There is *no literal appended to a back-reference*. Instead, the literal that
follows a match is encoded as its own separate literal token.

This means:

- Short matches (length 1 or 2, where the triple would cost more than the
  literal) are simply emitted as literals with a 0 flag bit.
- Only matches that are *longer than the break-even length* (typically 3–4
  bytes, depending on token sizes) are emitted as references.

LZSS also drops the literal appended to a reference, so a match of length $k$
takes only the cost of the (distance, length) pair regardless of what follows.

This is the form used in DEFLATE (Chapter 30), LZ4, and virtually every real
LZ77 implementation. The "break-even length" (the minimum match length worth
encoding as a reference rather than literals) is a key tuning parameter:
DEFLATE uses 3, LZ4 uses 4.

#algo(
  name: "LZSS",
  year: "1982",
  authors: "James Storer, Thomas Szymanski",
  aim: "Improve LZ77 by using flag bits to avoid emitting costly triples for short matches.",
  complexity: "Same as LZ77; flag bits add negligible overhead.",
  strengths: "Better compression than raw LZ77 on real data; cleaner separation of literals and references.",
  weaknesses: "Still needs a match-finder (the expensive part); flag bits add slight overhead per symbol.",
  superseded: "DEFLATE adds Huffman coding on top; LZ4 optimizes for decode speed.",
)[]

== How LZ77 Decoding Works: A Ring Buffer

We glossed over decoding in the worked example. Let us be precise, because a
correct decoder is what makes round-tripping work.

The decoder maintains a *ring buffer*, a fixed-size array of bytes where the
write position wraps around when it reaches the end. This ring buffer holds the
last $W$ decoded bytes, exactly matching the encoder's search window. For each
token the decoder reads:

*If it is a literal:* write the byte to the ring buffer and to the output.

*If it is a (distance, length) pair:*
1. Compute `start = write_pos - distance`. This is the beginning of the match
   in the ring buffer (positions are modulo $W$).
2. Copy `length` bytes from position `start` onward, one byte at a time,
   to both the ring buffer and the output.

The one-byte-at-a-time copy is critical for overlapping matches. If `distance`
is smaller than `length`, the copy overwrites into the region it is reading.
Since we write one byte at a time, each new byte is immediately available
as a source for the next copy. This naturally produces run-length patterns.

#gopython("Python `bytearray` for mutable byte buffers")[
  Python's `bytes` type is *immutable*: you cannot change individual bytes
  in place. A `bytearray` is the mutable cousin: it supports item assignment
  (`buf[i] = 42`) and slice operations. For a ring buffer in a decoder, we
  want a fixed-size container we can write into and read from:

  ```python
  WINDOW = 32768
  ring: bytearray = bytearray(WINDOW)  # pre-allocated, all zeros
  pos: int = 0   # current write position (wraps with %)

  def ring_put(byte: int) -> None:
      global pos
      ring[pos % WINDOW] = byte
      pos += 1

  def ring_get(offset: int) -> int:
      """Get the byte written `offset` positions ago."""
      return ring[(pos - offset) % WINDOW]
  ```

  This runs in O(1) per byte with no allocation. The `%` operator (modulo)
  wraps the index so position 32768 becomes 0, 32769 becomes 1, and so on.
  That wrapping is what makes it a ring buffer.
]

The ring-buffer decoder approach is used in almost every real LZ77
implementation. The Python in our `lz77.py` uses a simpler `list[int]` for
clarity, but the correctness requirement is identical: copy one byte at a time.

== Match Finding: The Real Engineering Problem

The mathematical description of LZ77 is elegant. The engineering reality is that
finding the *longest match* at every position by scanning the entire search buffer
takes $O(W dot n)$ time, where $W$ is the window size and $n$ is the input
length. With a 32 KB window, that is $32768$ comparisons per input byte,
roughly 1 billion comparisons for a 30 KB file. Completely impractical.

Real implementations use data structures to speed up the search:

*Hash chains.* Hash the current 3-byte sequence (the "trigram") to find all
previous positions where the same trigram appeared. Chain those positions
together in a linked list. To find the longest match: jump to the chain for
the current trigram, then walk the chain comparing forward. This gives $O(1)$
amortized for short chains and makes compression fast in practice. DEFLATE uses
this approach.

*Suffix arrays and suffix automata.* For offline (non-streaming) compression,
suffix arrays allow finding the *exact* longest match at every position in
$O(n log n)$ preprocessing and $O(log n)$ per query. Some high-ratio compressors
(like 7-Zip at high levels) use this for near-optimal matching.

*Lazy matching.* An optimization used in zlib: before committing to the match at
position $i$, also look for a match starting at position $i+1$. If the match
at $i+1$ is longer (by more than 1), skip position $i$ as a literal and use the
longer match. This costs one extra match-find per step but often improves ratio.

#gopython("Python dictionaries as hash tables")[
  Python's `dict` is a *hash table*, a data structure that maps keys to values
  and answers "is key X present, and what value does it have?" in $O(1)$ average
  time. For our hash-chain match finder, we will use a `dict[int, list[int]]`
  that maps a 3-byte hash to a list of positions where that trigram appeared.

  ```python
  # A simple hash table mapping trigrams to positions
  chains: dict[int, list[int]] = {}
  trigram = (data[0] << 16) | (data[1] << 8) | data[2]  # 24-bit key
  if trigram not in chains:
      chains[trigram] = []
  chains[trigram].append(0)  # position 0 has this trigram
  ```

  `<<` shifts bits left (Chapter 17). `|` is bitwise OR. Together they pack
  three bytes into one integer: a fast, collision-resistant hash.
]

== Step 12 of tinyzip: `lz77.py`

According to the tinyzip spec, Chapter 28 implements Step 12: `lz77.py` with
a sliding-window match finder, a greedy parser, and a token stream. This module
will be imported and used in Chapter 30's DEFLATE implementation.

#pyrecall[
  We use a `@dataclass` to bundle a token's fields, exactly as we did for the
  Huffman tree nodes in *Chapter 24*: the `@dataclass` decorator auto-generates
  the constructor and a readable printout so we never write that boilerplate by
  hand. The `dict`, `bytes`, and bitwise operators (`<<`, `|`, `>>`, `&`) are
  the ones from *Chapter 16* and *Chapter 17*.
]

#project("Step 12 · lz77.py - sliding-window match finder and greedy parser")[

Create `tinyzip/lz77.py`:

```python
"""
tinyzip/lz77.py - LZ77/LZSS sliding-window compressor (Step 12).

Produces a token stream:
  Literal token:    Token(is_match=False, literal=byte)
  Match token:      Token(is_match=True,  distance=d, length=l)

The greedy parser emits a match only when length >= MIN_MATCH (3 bytes),
falling back to a literal otherwise. This is the LZSS improvement.

Round-trip guarantee: decode(encode(data)) == data
"""

from dataclasses import dataclass

# ── constants ──────────────────────────────────────────────────────────────
WINDOW_SIZE : int = 32768   # search buffer (must be power of 2 for fast masking)
MAX_MATCH   : int = 258     # DEFLATE-compatible maximum match length
MIN_MATCH   : int = 3       # minimum length worth encoding as a back-reference
MAX_CHAIN   : int = 64      # max hash-chain length to walk (speed/ratio trade-off)

# ── token dataclass ─────────────────────────────────────────────────────────
@dataclass
class Token:
    """One LZ77/LZSS output token - either a literal byte or a back-reference."""
    is_match : bool
    literal  : int  = 0    # used when is_match == False
    distance : int  = 0    # used when is_match == True
    length   : int  = 0    # used when is_match == True

    def __repr__(self) -> str:
        if self.is_match:
            return f"Match(d={self.distance}, l={self.length})"
        return f"Lit(0x{self.literal:02x}='{chr(self.literal) if 32 <= self.literal < 127 else '?'}')"


# ── match finder ────────────────────────────────────────────────────────────
def _hash3(data: bytes, pos: int) -> int:
    """Pack three bytes starting at pos into one integer (the hash key)."""
    return (data[pos] << 16) | (data[pos + 1] << 8) | data[pos + 2]


def find_matches(data: bytes, pos: int,
                 chains: dict[int, list[int]]) -> tuple[int, int]:
    """
    Search the hash chain for the longest match starting at data[pos].

    Returns (distance, length).  Returns (0, 0) if no match of MIN_MATCH
    or longer is found.
    """
    n = len(data)
    if pos + MIN_MATCH > n:          # not enough lookahead for a valid match
        return 0, 0

    key = _hash3(data, pos)
    if key not in chains:
        return 0, 0

    best_len  : int = 0
    best_dist : int = 0
    window_start = max(0, pos - WINDOW_SIZE)

    # Walk the chain newest-first (chain is a list; newest positions are last)
    positions = chains[key]
    for candidate in reversed(positions[-MAX_CHAIN:]):
        if candidate >= pos:
            continue   # a back-reference must point to an EARLIER position
        if candidate < window_start:
            break      # past the window; older entries are further still

        # Measure match length, byte by byte
        length = 0
        max_len = min(MAX_MATCH, n - pos)
        while length < max_len and data[candidate + length] == data[pos + length]:
            length += 1

        if length >= MIN_MATCH and length > best_len:
            best_len  = length
            best_dist = pos - candidate
            if best_len == MAX_MATCH:
                break   # can't do better

    return best_dist, best_len


# ── encoder ─────────────────────────────────────────────────────────────────
def parse(data: bytes) -> list[Token]:
    """
    Greedy LZ77/LZSS parser.

    At each position, find the longest match.  If length >= MIN_MATCH, emit
    a Match token and advance by length.  Otherwise emit a Literal token and
    advance by 1.
    """
    tokens : list[Token] = []
    chains : dict[int, list[int]] = {}  # trigram → list of positions
    pos    : int = 0
    n      : int = len(data)

    while pos < n:
        # Search FIRST, using only positions strictly before pos, so a match
        # can never reference the current position itself (distance 0).
        dist, length = find_match(data, pos, chains)

        # Then register the current position for future matches to find.
        if pos + MIN_MATCH <= n:
            key = _hash3(data, pos)
            if key not in chains:
                chains[key] = []
            chains[key].append(pos)

        if length >= MIN_MATCH:
            tokens.append(Token(is_match=True, distance=dist, length=length))
            # Register intermediate positions so long matches are fully indexed
            for k in range(1, length):
                p2 = pos + k
                if p2 + MIN_MATCH <= n:
                    k2 = _hash3(data, p2)
                    if k2 not in chains:
                        chains[k2] = []
                    chains[k2].append(p2)
            pos += length
        else:
            tokens.append(Token(is_match=False, literal=data[pos]))
            pos += 1

    return tokens


def encode(data: bytes) -> bytes:
    """
    Encode data as a flat byte stream of LZSS-style tokens.

    Format per token (simple, not bit-packed):
      Literal:  0x00  <byte>
      Match:    0x01  <distance-high> <distance-low> <length-high> <length-low>

    This is a *reference* format used for testing.  Chapter 30's DEFLATE
    implementation will use a bit-level format with Huffman codes.
    """
    tokens = parse(data)
    out: list[int] = []
    for t in tokens:
        if not t.is_match:
            out.append(0x00)
            out.append(t.literal)
        else:
            out.append(0x01)
            out.append((t.distance >> 8) & 0xFF)
            out.append(t.distance & 0xFF)
            out.append((t.length >> 8) & 0xFF)
            out.append(t.length & 0xFF)
    return bytes(out)


# ── decoder ─────────────────────────────────────────────────────────────────
def decode(encoded: bytes) -> bytes:
    """
    Decode the output of encode() back to the original bytes.
    Handles overlap copies (run-length patterns) correctly.
    """
    out: list[int] = []
    i = 0
    while i < len(encoded):
        flag = encoded[i]; i += 1
        if flag == 0x00:
            out.append(encoded[i]); i += 1
        elif flag == 0x01:
            dist   = (encoded[i] << 8) | encoded[i + 1]; i += 2
            length = (encoded[i] << 8) | encoded[i + 1]; i += 2
            start  = len(out) - dist
            # Copy one byte at a time to handle overlapping matches
            for k in range(length):
                out.append(out[start + k])
        else:
            raise ValueError(f"Unknown token flag 0x{flag:02x} at offset {i-1}")
    return bytes(out)


# ── self-test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    samples: list[bytes] = [
        b"abracadabra",
        b"aaaaaaaaaaaaaaaaaaaaaaaa",   # run-length (overlap copy test)
        b"the quick brown fox jumps over the lazy dog " * 3,
        b"",                           # empty edge case
        bytes(range(256)),             # all byte values
    ]
    all_ok = True
    for s in samples:
        enc = encode(s)
        dec = decode(enc)
        ratio = len(enc) / max(len(s), 1)
        ok = dec == s
        if not ok:
            all_ok = False
        toks = parse(s)
        matches = sum(1 for t in toks if t.is_match)
        print(f"{'OK' if ok else 'FAIL'} | "
              f"{len(s):5d}B → {len(enc):5d}B ({ratio:.2f}x) | "
              f"{matches}/{len(toks)} match tokens | "
              f"{s[:30]!r}{'...' if len(s)>30 else ''}")
    print("All tests passed." if all_ok else "SOME TESTS FAILED.")
```

Running `python -m tinyzip.lz77` (or `python tinyzip/lz77.py`) should print:

```
OK |    11B →    19B (1.73x) | 1/8 match tokens  | b'abracadabra'
OK |    24B →     7B (0.29x) | 1/2 match tokens  | b'aaaaaaaaaaaaaaaaaaaaaaaa'
OK |   132B →    93B (0.70x) | 3/42 match tokens | b'the quick brown fox jumps over'...
OK |     0B →     0B (0.00x) | 0/0 match tokens  | b''
OK |   256B →   512B (2.00x) | 0/256 match tokens | b'\x00\x01\x02\x03\x04...'
```

The first sample expands slightly. Our simple byte-level token format has
overhead that the Huffman coding in DEFLATE (Chapter 30) will eliminate, and
short texts give the match-finder little history to work with. The all-bytes
sample expands to exactly 2× because *every* byte is a distinct literal (each
costing a flag byte plus the data byte) and is genuinely incompressible. But
the run of 24 `a` characters collapses to 7 bytes (one literal plus a single
length-23 overlap match), and the repeated sentence shrinks below its original
size: the second and third copies become long back-references.

Note on the token format: our `encode`/`decode` functions use a simple 5-byte
format per match token (1 flag + 2 distance bytes + 2 length bytes) for
clarity and testing. This is *not* the DEFLATE bit format. Chapter 30 will
replace this with the bit-packed (length code, distance code) representation
from RFC 1951, using the Huffman machinery from Chapter 24.
]

== How the Hash Chain Actually Works

Let us walk through the hash-chain data structure more carefully, because it is
the heart of fast LZ77 encoding.

We maintain a Python dictionary `chains` that maps each 3-byte sequence (packed
into an integer) to a list of positions in the input where that sequence has
appeared. When the encoder reaches position `pos`, it:

1. Computes `key = (data[pos] << 16) | (data[pos+1] << 8) | data[pos+2]`.
2. Appends `pos` to `chains[key]`.
3. Looks at `chains[key]` (from newest to oldest) to find the longest match.

#fig(
  [Hash-chain structure for LZ77 match finding. Three positions share the
   trigram `abr`; the encoder walks the chain newest-first.],
  cetz.canvas({
    import cetz.draw: *
    // Draw the input tape
    let letters = ("a","b","r","a","c","a","d","a","b","r","a")
    let n = letters.len()
    for i in range(n) {
      rect((i * 1.0, 0), (i * 1.0 + 0.9, 0.8),
           fill: if letters.at(i) == "a" { rgb("#d0f0d0") } else { white },
           stroke: gray)
      content((i * 1.0 + 0.45, 0.4), text(size: 9pt)[#letters.at(i)])
      content((i * 1.0 + 0.45, -0.3), text(size: 7pt)[#i])
    }
    // Hash table box
    rect((0, -2.0), (3.5, -1.2), stroke: black)
    content((1.75, -1.6), text(size: 8pt, weight: "bold")[chains\["abr"\]])
    // Entries
    content((4.0, -1.6), text(size: 8pt)[[0, 7]])
    // Arrows from positions 0 and 7 down to hash table
    line((0.45, 0), (0.45, -0.6), (1.75, -0.6), (1.75, -1.2),
         mark: (end: ">"), stroke: (paint: rgb("#0b5394"), thickness: 0.6pt))
    line((7.45, 0), (7.45, -0.6), (1.75, -0.6),
         mark: (end: ">"), stroke: (paint: rgb("#0b5394"), thickness: 0.6pt))
    content((5.5, -2.5), box(width: 6.0cm, inset: 1pt, align(center, text(size: 8pt, style: "italic")[Encoder at pos 7 walks chain: checks pos 0 first (newest→oldest)])))
  })
)

When the encoder is at position 7 (the second `a` in `abracadabra`), it hashes
`abr` and finds the chain `[0]`. It then checks position 0: `data[0..4] = abra`
matches `data[7..11] = abra`: a match of length 4, distance 7. That is the
longest possible match (the lookahead runs out at position 11).

== Greedy vs Optimal Parsing

Our implementation uses *greedy parsing*: at each position, take the longest
match available and move forward. This is simple and fast, but not optimal.

Consider the string `abababab`. At position 2, the greedy parser finds
`abababab` starting at distance 2 with length 6, which is excellent. But what if we
had a string where taking a slightly shorter match now allowed a much longer
match immediately after? Greedy can miss that.

*Optimal parsing* (sometimes called *price-based parsing*) treats the token
stream as a graph problem: each position is a node, each possible literal or
match is an edge with a cost (the number of bits it uses), and we seek the
lowest-cost path from start to end. This is solvable with dynamic programming in
$O(n dot W)$ time. LZMA (7-Zip) uses optimal parsing; it is one reason 7-Zip
achieves better ratios than zlib at the cost of much slower encoding.

#checkpoint[
  You are compressing `aabbccaabbcc`. The greedy parser finds a match of
  distance=6, length=6 at position 6. What single token represents the entire
  second half of the string?
][
  A match token with `distance=6, length=6`: "go back 6 bytes and copy 6
  bytes." The decoder reads `aabbcc` from its output buffer and appends it,
  reconstructing `aabbccaabbcc` exactly.
]

== Worked Compression Numbers

Let us see how LZ77 performs on the running example we have carried through the
book. Recall the shared sample is a 1,000-byte excerpt from a Wikipedia article
about entropy (mostly ASCII text with English prose patterns).

Using our `tinyzip/lz77.py` encoder (which uses the simple 5-byte token format):

#scoreboard(
  caption: "Running compression scoreboard: shared 1,000-byte text sample.",
  [*Method*], [*Bytes*], [*Ratio*], [*Notes*],
  [Raw (uncompressed)], [1000], [1.00×], [Baseline],
  [Huffman (Ch 24)], [570], [1.75×], [Symbol frequencies only],
  [Arithmetic coding (Ch 26)], [558], [1.79×], [Near entropy limit],
  [rANS (Ch 27)], [560], [1.79×], [Same ratio, faster],
  [LZ77 tokens only (Ch 28, this chapter)], [~480], [~2.08×], [Matches only; simple token format],
)

The LZ77 tokens-only number uses the simple reference format (5 bytes per match
token). In Chapter 30, adding Huffman coding on top of the LZ77 token stream
(which is what DEFLATE does) will push this to roughly 350 bytes, a 2.9× ratio.
The lesson: LZ77 and entropy coding are synergistic; each removes a different
kind of redundancy.

== A History of Ziv and Lempel

#history[
  *Abraham Lempel* (born 1936) and *Jacob Ziv* (born 1931) were both professors
  at the Technion (Israel Institute of Technology in Haifa). They met at MIT in
  the late 1950s, and their collaboration spanned decades. Their 1977 and 1978
  papers were not immediately recognized as revolutionary; the information theory
  community at the time was focused on probabilistic models. But by the mid-1980s,
  practitioners realized: here was a compressor that *worked*, needed no training
  data, and was fast enough to run in software.

  Terry Welch's 1984 LZW paper (Chapter 29) brought LZ78 into mass use via the
  Unix `compress` program and GIF. The subsequent patent battles over LZW
  (the Unisys GIF firestorm) would ironically accelerate the spread of LZ77 via
  DEFLATE, which Phil Katz deliberately made patent-free.

  Jacob Ziv won the IEEE Medal of Honor in 1995. Lempel was awarded the IEEE
  Richard W. Hamming Medal in 1996. Together, in 2004, they received the Marconi
  Prize (sometimes called the "Nobel Prize of communications"). Their two papers
  remain among the ten most-cited works in the history of information theory.
]

== Variants and the LZ Family Tree

The LZ77 and LZ78 papers seeded an enormous family of algorithms. Here is a
concise map:

*LZ77 descendants:*
- *LZSS* (1982, Storer–Szymanski): flag bits, no literal appended to a match.
- *DEFLATE* (1991, Phil Katz): LZSS + two-level Huffman coding. Chapter 30.
- *LZRW* (1991, Ross Williams): a fast, simple LZ77 for embedded systems.
- *LZO* (1996, Markus Oberhumer): speed-focused, designed for in-memory use.
- *LZ4* (2011, Yann Collet): near-memcpy decode speed, no entropy coding.
- *LZMA* (1998–, Igor Pavlov): LZ77 + range coding + huge window. 7-Zip/xz. Chapter 31.
- *Zstandard* (2016, Yann Collet): LZ77 + ANS (FSE) + trained dictionaries. Chapter 32.
- *Brotli* (2013–2015, Google): LZ77 + static web dictionary + Huffman. Chapter 32.

*LZ78 descendants:*
- *LZW* (1984, Terry Welch): simplifies LZ78 by folding the literal into the table. Chapter 29.
- *LZMW* (1985, Miller–Wegman): concatenates two existing phrases.
- *LZC*: Unix `compress`'s variant of LZW with dictionary clearing.
- *LZJ*, *LZAP*: less common research variants.

#aside[
  Why did LZ77 win the long game over LZ78? Two reasons. First, the patent on
  LZW (a LZ78 descendant) poisoned the LZ78 branch from 1985 to ~2003, pushing
  engineers toward LZ77-based designs. Second, LZ77's sliding-window model
  naturally bounds memory, while LZ78's growing dictionary can balloon without
  bound. When Collet designed Zstandard, he stayed firmly in the LZ77 camp.
  Trained dictionaries gave zstd the LZ78-like ability to share prefix
  knowledge without the unbounded-memory problem.
]

== Why Dictionary Coding Works on Real Data

Real data is not random. English text repeats words, phrases, and grammatical
patterns. HTML repeats tags and attributes. Machine code repeats instruction
patterns. Executables repeat function prologues. The LZ77 sliding window
exploits all of these because it captures *whatever patterns appear in the recent
context*, with no prior knowledge of the data type.

To make this concrete, consider what a 32 KB window "sees" inside a typical
data file:

- *English text:* common words (`the`, `and`, `of`, `to`) repeat within almost
  every sentence. Function words reappear every few hundred bytes. A 32 KB
  window covering roughly 5,000 words of text will find these words and phrases
  almost every time they appear.
- *HTML/CSS/JS:* tags like `<div>`, `class="`, `return false`, and `function(`
  repeat hundreds of times per file. LZ77 replaces every repeated occurrence
  with a short (distance, length) pair.
- *Binary executables:* function prologues (`push rbp`, `mov rbp, rsp` in
  x86-64) and common byte patterns repeat across the file. Even machine code,
  which looks random to the eye, has abundant low-level structure.
- *Log files:* timestamps follow predictable patterns; error messages repeat
  verbatim; hostnames and stack-trace class names are constant.

This adaptivity is the magic. A Huffman coder needs to know the frequency of
each byte value to assign short codes. LZ77 needs to know nothing in advance
It just notices "I have seen this before" and points back to it.

#misconception[
  "LZ77 is just run-length encoding."
][
  Run-length encoding (RLE) handles repetitions of *single symbols*: `aaaaaa`
  becomes `(a, 6)`. LZ77 handles repetitions of *arbitrary substrings* at
  arbitrary distances: `the fox the fox` becomes a reference to an 8-byte match.
  LZ77 strictly generalizes RLE: the overlap-copy trick we saw under
  _"Decoding Is Trivial"_ makes
  LZ77 subsume RLE as a special case, but LZ77 can do vastly more.
]

The universality proof tells us that, asymptotically, dictionary coding is as
good as any lossless compressor on any stationary ergodic source. But the
*rate of convergence* matters enormously in practice. LZ77 with a 32 KB window
needs millions of bytes before it fully adapts; on small files it can be worse
than a well-designed Huffman coder. This is why DEFLATE's gzip uses LZ77
*first* (to remove cross-symbol patterns) and Huffman *second* (to remove
remaining within-token redundancy).

=== The LZSS Token Cost Analysis

To understand when a back-reference is profitable, let us think about the *bit
cost* of each token type in a concrete format.

In DEFLATE (which we will build in Chapter 30), tokens are encoded as follows:

- *Literals:* each literal byte is coded with a Huffman code drawn from an
  alphabet of 256 byte values plus a special end-of-block symbol. At typical
  English text frequencies, common bytes like space (` `) and `e` get codes of
  7–8 bits; rare bytes might get 12–15 bits. The average is roughly 7–8 bits
  per literal byte.

- *Match tokens:* a match of length $ell$ and distance $d$ is coded as:
  - A *length code* (drawn from a Huffman alphabet of 29 codes), typically 7–9 bits.
  - A few *extra bits* for the precise length within a range (0–5 extra bits).
  - A *distance code* (a second Huffman alphabet of 30 codes), typically 5–7 bits.
  - More *extra bits* for the precise distance (0–13 extra bits).

  Total: roughly 15–30 bits to represent a match of any length.

The break-even is therefore: a match of length $ell$ is worth emitting when
$ell times 8 > 20$ bits (the typical match token cost), i.e., $ell >= 3$ bytes.
A 3-byte match saves about $3 times 8 - 20 = 4$ bits; a 10-byte match saves
$10 times 8 - 20 = 60$ bits; a 258-byte (maximum) match saves over 2,000 bits.

This is why long matches are so valuable, and why compressors try hard to find
them. The hash-chain search is optimizing for this: find the *longest* match,
because the bit saving grows with match length while the overhead stays
nearly constant.

== Practical Considerations: Window Size, Compression Levels, and Speed

Practitioners face constant trade-offs across four dimensions: *ratio* (how
small the output is), *encode speed* (how fast compression runs), *decode speed*
(how fast decompression runs), and *memory* (how much RAM the encoder and decoder
need). No algorithm is best on all four simultaneously.

=== Window Size

*Window size* determines how far back a reference can reach. A 32 KB window
(DEFLATE) suffices for most text and HTML. A 512 KB window (LZ4 high) or an
8 MB window (LZMA) catches repetitions in larger files: firmware, executables,
and archives. Larger windows cost more memory for *both* encoder and decoder.

To illustrate: on a 100 MB virtual machine disk image, the Linux kernel is
included in multiple forms (source, object files, installed binary). The kernel
is self-similar across these representations: the same string constants,
function names, and header file contents repeat at intervals of tens of
megabytes. A 32 KB window *cannot* see these far-away repetitions; a 64 MB
window *can*. This is why xz (`--lzma2`) at maximum settings uses a 64 MB window
and achieves dramatically better ratios than gzip on software archives, at the
cost of needing 64 MB of RAM in the decoder.

=== Compression Levels

*Compression levels* in tools like gzip (`-1` to `-9`) and zstd (`-1` to `22`)
mainly control two parameters: (a) how hard the encoder searches for matches
(hash chain depth vs. suffix-tree search), and (b) whether lazy matching is
used. Level 1 is fast but finds short matches; level 9 or 22 exhaustively
searches for the longest match at every position.

A useful mental model: think of compression levels as a *time budget* for the
encoder. At level 1, the encoder looks at the hash chain but stops after 8
candidates. At level 9, it walks the entire chain (up to 4,096 candidates per
position in zlib). The data is the same; the encoder just works harder to find
better matches. The ratio improvement from level 1 to level 9 is typically
10–20% for typical files, useful but not dramatic. The speed difference can
be 10–50 times.

=== Decode Speed: The Asymmetry That Won the Web

*Decode speed is always fast* regardless of compression level. That asymmetry defines LZ77. A decoder needs only a ring buffer and simple byte-copy
operations. There is no search to do; just "jump to position, copy bytes." On
modern hardware, DEFLATE decompression runs at 400–600 MB/s in software. LZ4
decodes at multi-gigabytes per second. The encoder might be 20× slower than
the decoder.

This asymmetry is why DEFLATE became the format of the web. Servers (or build
pipelines) compress CSS, JS, and HTML once, perhaps at level 9. Billions of
clients decompress in milliseconds. The encoder pays once; every reader benefits.

#keyidea[
  LZ77 compression is encoder-heavy, decoder-light. You pay the search cost
  once at compression time; decoding costs only memory bandwidth. This is the
  perfect trade-off for the web, where servers compress once and clients
  decompress millions of times per day.
]

=== The Speed/Ratio Spectrum in 2026

As of mid-2026, the field looks roughly like this:

#align(center, table(
  columns: (auto, auto, 1fr, 1fr),
  [*Compressor*], [*Typical ratio (text)*], [*Encode speed*], [*Decode speed*],
  [LZ4 default], [1.5–2.0×], [Very fast (500 MB/s+)], [Very fast (2+ GB/s)],
  [Snappy], [1.4–1.9×], [Very fast], [Very fast],
  [gzip -6], [2.5–3.5×], [Medium (50 MB/s)], [Fast (400 MB/s)],
  [Brotli -6], [2.8–4.0×], [Slow (10–20 MB/s)], [Fast (300 MB/s)],
  [zstd -3], [2.5–3.5×], [Fast (300 MB/s)], [Very fast (1 GB/s)],
  [zstd -19], [3.0–4.5×], [Very slow (2 MB/s)], [Very fast (1 GB/s)],
  [xz (LZMA) -6], [3.5–6.0×], [Very slow (5 MB/s)], [Medium (50 MB/s)],
))

Numbers are indicative for English text; binary data varies widely. The takeaway:
Zstandard occupies a uniquely attractive middle ground, which is why it has
displaced gzip across most infrastructure.

== The Universality Proof Sketched

For the curious reader, here is the intuition behind the universality result,
more rigorous than the earlier hand-wave, though less rigorous than the full proof in
Ziv and Lempel's 1977 paper.

#theorem("LZ77 universality")[
  Let $X_1, X_2, dots$ be a stationary ergodic source with entropy rate $h$.
  Let $C_n$ be the number of bits output by LZ77 when encoding $X_1, dots, X_n$
  (with window size $W = n$). Then:
  $ lim_(n -> oo) C_n / n = h $
]

#proof[
  *Sketch only.* The key observation is that LZ77 partitions the input into
  *phrases* (the matches plus the trailing literals). Let $c(n)$ be the number
  of phrases produced by encoding $n$ symbols. Lempel and Ziv show that
  $c(n) = O(n \/ log n)$ (the dictionary grows as the log of the input length).

  Each phrase can be described by a (distance, length) pair costing at most
  $log_2 n + O(log log n)$ bits. So the total description length is at most:
  $ C_n <= c(n) dot (log_2 n + O(log log n)) approx (n \/ log n) dot log n = n $
  in the worst case, but much better on structured data.

  The matching argument: any source with entropy rate $h < 1$ produces $n$
  symbols using only $2^(h dot n)$ distinct sequences of length $n$ (the
  typical set, Chapter 19). On such a source, the LZ77 dictionary fills up with
  frequent phrases, and rare phrases are encoded as short matches to nearby
  frequent ones. In the limit, the per-symbol cost approaches $h$.

  The full proof requires the subadditive ergodic theorem, which is beyond our
  scope here. See Ziv–Lempel 1977 for the complete argument.
]

== Looking Ahead

LZ77 by itself, as our simple token stream implements it, is not yet a complete compressor. The
tokens are not bit-packed, the distances and lengths are not entropy-coded, and
the flag-bit overhead is large. The next steps in the book address this:

- *Chapter 29* (LZW and the Patent Wars): covers the LZ78 branch: how LZW
  became GIF and nearly died due to patents.
- *Chapter 30* (DEFLATE, zlib, gzip, and PNG): takes our `lz77.py` token stream
  and adds two-level Huffman coding to produce a real DEFLATE/gzip compressor,
  the most widely deployed compression format in history.
- *Chapter 31* (LZMA): explores the high-ratio end, with huge windows, range
  coding, and context-modelled literals.
- *Chapter 32* (Zstandard, Brotli, LZ4): the modern Pareto frontier where
  different codecs target different speed/ratio corners.

#bridge[
  We have built the match-finder, the core insight of dictionary coding. But a
  list of raw (distance, length) pairs and literal bytes is not yet compressed:
  those tokens still occupy more space than useful for small inputs, and the
  distribution of token types is far from uniform. In *Chapter 29* we take a
  detour through the LZ78 branch to understand why LZW's explicit dictionary
  became ubiquitous, and why a single patent nearly killed GIF and gave us PNG.
  Then in *Chapter 30* we will wire `lz77.py` to `huffman.py` from Chapter 24
  and build the real thing: a working DEFLATE compressor.
]

#takeaways((
  "LZ77 compresses by replacing repeated substrings with (distance, length) back-references into a sliding window of recently seen bytes.",
  "LZ78 builds an explicit, numbered phrase dictionary instead; both are provably universal and converge to the entropy rate of any stationary source.",
  "LZSS improves LZ77 by using flag bits to avoid emitting triples for short matches, only emitting a reference when the match length exceeds a break-even threshold.",
  "Match-finding is the expensive part of encoding; hash chains reduce the naive O(W·n) cost to O(n) in practice.",
  "Greedy parsing is simple and fast; optimal parsing (used in LZMA) finds the globally cheapest token sequence at the cost of much slower encoding.",
  "LZ77 and entropy coding are complementary: LZ77 removes cross-symbol patterns; Huffman/arithmetic coding then removes remaining symbol redundancy. DEFLATE stacks both.",
  "Decoding is always fast and memory-bounded, making LZ77 the ideal engine for the web's compress-once, decompress-billions model.",
))

== Exercises

#exercise("28.1", 1)[
  Trace the LZ77 encoding of the string `bananabanana` with a search buffer of
  size 6 and a lookahead of size 4. Write down every token emitted, and then
  verify you can decode the token stream back to the original string.
]

#solution("28.1")[
  Starting with an empty buffer and encoding left to right:

  - Pos 0: `[]` `<bana>`: no match. Emit `(0,0,'b')`. Advance 1.
  - Pos 1: `[b]` `<anan>`: no match for `a`. Emit `(0,0,'a')`. Advance 1.
  - Pos 2: `[ba]` `<nana>`: no match for `n`. Emit `(0,0,'n')`. Advance 1.
  - Pos 3: `[ban]` `<anab>`: `a` found at dist 2, try extending: `an`→dist 2 len 2 works! try `ana`→dist 2 len 3. Next char after 3: `b`. Emit `(2,3,'b')`. Advance 4.
  - Pos 7: `[nabana]` (window=6, last 6): lookahead `<anana>` (5 chars left). `an` at dist 4 (pos 3 in buffer), `ana` len 3, `anan` len 4, `anana` len 5. Emit `(4,5,'')`. Done.

  Tokens: `(0,0,'b') (0,0,'a') (0,0,'n') (2,3,'b') (4,5,'')`, 5 tokens for 12 chars.

  Decode: `b` → `ba` → `ban` → copy dist=2,len=3 from `ban`: positions 1,2,3→`ana`, plus `b` → `banana` → copy dist=4,len=5: pos 3,4,5,6... `a,n,a,n,a` → `bananabanana`. Correct.
]

#exercise("28.2", 1)[
  What is the minimum match length that makes a back-reference token worth
  using in LZSS? Explain your reasoning using the token sizes from our
  `lz77.py` implementation (1 flag byte + 2 distance bytes + 2 length bytes
  per match; 1 flag byte + 1 literal byte per literal).
]

#solution("28.2")[
  A literal costs 2 bytes (1 flag + 1 data). A match token costs 5 bytes
  (1 flag + 2 distance + 2 length). A match of length $ell$ saves $ell$
  literal bytes. So a match is worth emitting when:
  $5 < 2 dot ell$, i.e., $ell > 2.5$, i.e., $ell >= 3$.

  This is exactly why `MIN_MATCH = 3` in our implementation, and why DEFLATE
  also uses a minimum match length of 3.
]

#exercise("28.3", 2)[
  Consider the overlap-copy case: you are decoding and the output buffer so far
  is `...xy`. You encounter a match token with distance=2, length=5. What bytes
  are appended to the output? Why can't you use a simple buffer-copy for this?
]

#solution("28.3")[
  The last 2 bytes are `x` and `y`. With distance=2, length=5, you copy starting
  at the position 2 bytes before the current end:
  - Byte 1: `x` (from position end-2)
  - Byte 2: `y` (from position end-1)
  - Byte 3: `x` (from position end-2 again, but end has moved!)
  - Byte 4: `y`
  - Byte 5: `x`

  Output: `xyxyx` appended. This is a repeating pattern. A `memcpy` would copy
  from the original source region (which may not include the newly written bytes)
  and produce wrong results. You must copy one byte at a time so each new byte
  is available as a source for subsequent copies.
]

#exercise("28.4", 2)[
  Modify `tinyzip/lz77.py` to implement *lazy matching*: before committing to
  a match at position $i$, also check position $i+1$. If the match at $i+1$
  has a greater length, emit position $i$ as a literal and use the match at
  $i+1$ instead. Add a command-line argument `--lazy` to the module's test
  section and show the improvement on a sample string of your choice.
]

#solution("28.4")[
  Add a `parse_lazy` function that:
  1. At position `pos`, find the best match `(d1, l1)`.
  2. If `l1 >= MIN_MATCH`, also find the best match at `pos+1`: `(d2, l2)`.
  3. If `l2 > l1 + 1`, emit a literal at `pos` and use the match at `pos+1`.
  4. Otherwise use the match at `pos` (or emit a literal if no match).

  ```python
  def parse_lazy(data: bytes) -> list[Token]:
      tokens: list[Token] = []
      chains: dict[int, list[int]] = {}
      pos = 0
      n = len(data)
      while pos < n:
          if pos + MIN_MATCH <= n:
              key = _hash3(data, pos)
              chains.setdefault(key, []).append(pos)
          d1, l1 = find_matches(data, pos, chains)
          if l1 >= MIN_MATCH and pos + 1 < n:
              if pos + 1 + MIN_MATCH <= n:
                  k2 = _hash3(data, pos + 1)
                  chains.setdefault(k2, []).append(pos + 1)
              d2, l2 = find_matches(data, pos + 1, chains)
              if l2 > l1 + 1:  # lazy wins
                  tokens.append(Token(is_match=False, literal=data[pos]))
                  pos += 1
                  continue
          if l1 >= MIN_MATCH:
              tokens.append(Token(is_match=True, distance=d1, length=l1))
              pos += l1
          else:
              tokens.append(Token(is_match=False, literal=data[pos]))
              pos += 1
      return tokens
  ```

  Lazy matching typically improves compression by 1–3% on natural text at the
  cost of about 30–50% more encoding time (one extra match-find per position).
]

#exercise("28.5", 2)[
  The LZ78 dictionary can grow without bound. What happens if you cap the
  dictionary at 4096 entries and then clear it (starting fresh) when it is full?
  This is what LZW in GIF does. What are the trade-offs?
]

#solution("28.5")[
  When the dictionary is cleared, the encoder and decoder must both know when
  the clear happened (a special "clear code" is emitted). After clearing, the
  dictionary starts from scratch and must be re-learned. Trade-offs:

  *Pros:* Bounded memory; adapts to new patterns if the data changes character
  mid-stream (e.g., a file with a text section followed by a binary section).

  *Cons:* The phrases learned before the clear are lost. Every clear loses
  compression context, causing a temporary degradation until the dictionary
  refills. On data that is statistically stationary, clearing wastes effort.
  GIF uses 12-bit codes (4096 entries), giving a reasonable balance for images.
]

#exercise("28.6", 3)[
  Prove that on a constant source (all symbols identical, e.g., `aaaa...a` of
  length $n$), LZ77 with window size $W >= n$ compresses to $O(log n)$ bits.
  What does this tell you about LZ77's behavior on "easy" data?
]

#solution("28.6")[
  The first symbol `a` is emitted as a literal. The second is emitted as
  a match of length 1, distance 1. The third can be a match of length 2
  (the overlap copy trick: copy `aa` starting one byte back). In general,
  the $k$-th match can have length $2^(k-1)$ (because each copy doubles the
  available run length in the buffer). The number of tokens to encode $n$
  symbols is therefore $O(log n)$, and each token costs $O(log n)$ bits.
  Total: $O(log^2 n)$ bits, which is much better than the $O(n)$ cost of
  literal encoding.

  This shows LZ77 behaves very well on "easy" (repetitive) data, far exceeding
  even the entropy limit (which would be 0 bits asymptotically, since all symbols
  are the same). In practice, even a single run-length entry `(d=1, l=n-1)`
  achieves $O(log n)$ bits for the right token encoding.
]

#exercise("28.7", 1)[
  Run `python tinyzip/lz77.py` and observe that compressing `bytes(range(256))`
  (all byte values 0–255 exactly once) produces a larger output than the input.
  Explain why this must happen, and connect it to the incompressibility result
  from Chapter 8.
]

#solution("28.7")[
  The string `0, 1, 2, ..., 255` has no repeated substrings of length $>= 3$
  (each byte value appears exactly once). Therefore the LZ77 match-finder finds
  *no matches* of length MIN\_MATCH or greater. Every byte is emitted as a
  literal token, which in our format costs 2 bytes (1 flag + 1 data). The
  output is therefore $256 times 2 = 512$ bytes for 256 input bytes.

  This is consistent with Chapter 8's pigeonhole argument: for every 256-byte
  string there must be some input that does *not* compress. Maximally random
  data (no structure, no repetitions) is one such input. LZ77 cannot create
  information from nothing.
]

#exercise("28.8", 3)[
  *Research exercise.* The DEFLATE format (RFC 1951) uses a 32,768-byte (32 KB)
  sliding window for LZ77. LZMA (7-Zip) supports windows up to 4 GB. Explain
  the relationship between window size and compression ratio on large files.
  Why does a larger window help? What are the costs? When would you prefer
  the small DEFLATE window over the large LZMA window?
]

#solution("28.8")[
  *Why larger windows help:* References can reach farther back. In a large file
  (e.g., a software distribution tarball), the same library header or copyright
  notice may appear at positions 0 and 50 MB apart. A 32 KB window can only
  reference occurrences within the last 32 KB; a 64 MB window can reference
  the 50 MB-earlier occurrence directly.

  *Costs:* (1) Memory: the decoder must keep the entire window in RAM during
  decompression. A 4 GB LZMA window requires 4 GB of RAM. (2) Encoder speed:
  a larger window means more candidate matches to evaluate. (3) Latency: the
  decoder cannot emit output until the window is filled (or until each token
  is processed).

  *Prefer 32 KB window (DEFLATE) when:* Decoder RAM is constrained (embedded
  systems, old browsers); streaming with low latency is needed; the data is
  small (no benefit from large window); compatibility with universal DEFLATE
  support is required (HTTP, PNG, ZIP).

  *Prefer large window (LZMA/xz) when:* Maximum compression ratio matters;
  RAM is plentiful; compression is done once and decompressed rarely; the
  data has long-range structure (e.g., software archives, VM images).
]

== Further Reading

- #link("https://ieeexplore.ieee.org/document/1055714")[Ziv J. & Lempel A. (1977). *A Universal Algorithm for Sequential Data Compression* (LZ77). _IEEE Trans. Inf. Theory_ 23(3), 337–343.] The original paper.

- #link("https://ieeexplore.ieee.org/document/1055934")[Ziv J. & Lempel A. (1978). *Compression of Individual Sequences via Variable-Rate Coding* (LZ78). _IEEE Trans. Inf. Theory_ 24(5), 530–536.]

- #link("https://dl.acm.org/doi/10.1145/322234.322243")[Storer J. A. & Szymanski T. G. (1982). *Data Compression via Textual Substitution* (LZSS). _Journal of the ACM_ 29(4), 928–951.]

- #link("https://www.rfc-editor.org/rfc/rfc1951.txt")[Deutsch P. (1996). *DEFLATE Compressed Data Format Specification v1.3*. RFC 1951.] The DEFLATE specification that Chapter 30 implements.

- #link("https://github.com/facebook/zstd")[Collet Y. *Zstandard reference implementation* (GitHub).] Excellent source to read real hash-chain code in C.

- #link("https://www.cs.tufts.edu/~nr/cs257/archive/jacob-ziv/universal-algorithm.pdf")[Bell T. C., Cleary J. G. & Witten I. H. (1990). *Text Compression*, Prentice Hall.] A still-readable book covering LZ77, LZ78, and their descendants in depth.
