#import "../lib.typ": *
#import "@preview/cetz:0.4.2"

= Lossless and Speech Coding

#epigraph[
  There is a big difference between a recording and a performance. A recording tries to
  capture the air pressure itself. A vocoder captures the _idea_ of what was said, and
  reconstructs the air pressure from scratch.
][
  Loosely paraphrased from Manfred Schroeder, inventor of CELP, _c._ 1985
]

Here is a puzzle that will sharpen the lesson of the entire Volume III arc. Suppose you
hand an audio compressor two recordings: the first is a full orchestral symphony (rich
harmonics, dynamic drums, soaring strings). The second is a phone call recorded in a quiet
room, one person talking, nothing else. The compressor using MP3 or AAC (Chapters 47 and
48) will squeeze both dramatically, ten-to-one or better, by exploiting what the human
ear cannot hear. But now give the same files to a _lossless_ compressor, and something
strange happens: the symphony ends up about half its original size, while the phone call
ends up at less than one-tenth. Why the colossal difference?

The answer is that lossless compression can only remove statistical redundancy (patterns
that repeat in the numbers), whereas lossy perceptual coding removes _biological_ redundancy:
the sounds your ear would have ignored anyway. Music is rich, noisy, and statistically
complex, so the lossless coder cannot do much. Speech, by contrast, is generated by a
surprisingly simple mechanical process - air blown through a pipe with resonant chambers -
and that process has deep, exploitable structure. A codec that models the _source_ of speech
instead of the waveform itself can achieve extraordinary compression. That is what this
chapter is about.

We will cover two distinct families. First, the lossless audio world: FLAC, ALAC,
WavPack, and Monkey's Audio. I'll describe what they share, how they exploit short-term linear
structure in audio samples, and why 50–60 % reduction is about as good as lossless gets
for music. Second, the speech coding world: LPC-10, CELP, ACELP, AMR, and EVS. These are codecs
that discard far more than any perceptual model would ever dare, because they know exactly
what the human vocal tract can and cannot produce.

#recap[
  Chapters 46 and 47 taught us psychoacoustics and MP3: the idea of discarding signal
  energy that falls below the masking threshold. Chapters 48 and 49 added AAC and Opus.
  Before that, Chapters 37–39 covered the DCT and quantization: controlled rounding that
  trades quality for bits. Chapter 18 gave us Shannon entropy (the hard floor on lossless
  size), and Chapter 19 proved no lossless code can beat it. Chapter 25 built the integer
  and universal codes (unary, Elias, Golomb–Rice) we will reuse for residuals here, and
  Chapter 35 introduced the Burrows–Wheeler Transform, showing that even lossless coders
  benefit from transforming data into a friendlier shape before entropy coding. Now we
  apply the same "transform first, then code" philosophy to audio: first for the goal of
  perfect reconstruction, then for the goal of intelligible speech at near-impossibly-low
  bitrates.
]

#objectives((
  [Explain why lossless audio compression achieves only 40–60 % reduction on music, and
   contrast that with the 90 %+ achievable by perceptual codecs.],
  [Describe linear predictive coding (LPC): what it predicts, what the residual is, and why
   Rice/Golomb codes are near-optimal for encoding that residual.],
  [Name the four major lossless audio codecs (FLAC, ALAC, WavPack, Monkey's Audio), state
   who created each, its licence, and its distinctive design choice.],
  [Define the vocoder concept: what is the source model, what are the parameters, and how do
   they reconstruct speech at the decoder?],
  [Trace the evolution from LPC-10 (2400 bps) through CELP (1985) to ACELP, AMR-NB,
   AMR-WB, and EVS, naming key people and dates.],
  [Explain what "algebraic codebook" means in ACELP and why it made the algorithm fast
   enough to run on a mobile phone.],
))

== Why Lossless Has a Ceiling

Before we meet any specific codec, we need to understand the ceiling. In Chapter 18 we
learned that Shannon entropy sets a hard lower bound on how many bits any lossless
compression scheme can use per symbol, and Chapter 19 proved that bound is unbeatable.
Averaged over a long piece of music, that bound is stubbornly high. Why?

Recall from Chapter 18 that entropy is high when the probability distribution over symbols
is spread out: when the next value is hard to predict. A CD-quality audio sample is a
16-bit integer in the range −32,768 to 32,767. Silence has very low entropy (it is just
zeros). But a crash cymbal, a piano chord, or a plucked guitar string produces sample
values that jump erratically over thousands of different values from moment to moment.
Generic lossless compression, whether Huffman codes or arithmetic coding, cannot gain much
traction.

The clever move, used by every lossless audio codec, is to avoid compressing the raw
samples at all. Instead:

1. *Predict* each sample from its recent neighbours using a mathematical formula.
2. Compute the *residual* (the difference between the prediction and the actual sample).
3. *Entropy-code* the residual.

The residual is much smaller in magnitude than the original sample. Where a sample might
range ±30,000, the residual (the part the predictor got wrong) might typically range
only ±200. A small-magnitude distribution is far more compressible.

#keyidea[
  Lossless audio coding = linear prediction (to produce small residuals) +
  entropy coding (to pack the residuals compactly). The predictor is tuned to
  audio; the entropy coder is often Rice/Golomb because the residuals follow a
  Laplacian-like distribution that makes those codes near-optimal.
]

Even so, the ceiling is real. The residuals of a complex musical passage are still
statistically diverse: they are not all near zero, and their entropy cannot be made
arbitrarily small without discarding information. For typical 44.1 kHz 16-bit stereo
music, lossless codecs reduce files to 50–70 % of raw PCM size. The remaining 30–50 %
can only be removed by throwing something away.

== Linear Predictive Coding (LPC): the Shared Engine

Every codec in this chapter, both lossless audio and speech, is built around the same
core idea: *linear predictive coding*, or LPC.

=== The Basic Idea

Suppose you have a sequence of audio samples: $x_1, x_2, x_3, dots$. The sample at time
$n$ is $x_n$. A *linear predictor of order $p$* estimates $x_n$ as a weighted sum of the
$p$ previous samples:

$ hat(x)_n = a_1 x_(n-1) + a_2 x_(n-2) + dots + a_p x_(n-p) $

The weights $a_1, a_2, dots, a_p$ are called *predictor coefficients*. The error (the
difference between prediction and reality) is the *residual*:

$ e_n = x_n - hat(x)_n $

The goal is to choose the coefficients so that the residuals $e_n$ are as small as
possible, in the mean-squared-error sense.

#mathrecall[Matrices and vectors are from Chapter 12; $E[dot]$, the expectation (a
probability-weighted average), is from Chapter 10. A matrix equation $R bold(a) = bold(r)$
is just a compact way to write $p$ ordinary linear equations in the $p$ unknowns $a_1 dots
a_p$.]

#gomaths("Linear Prediction and Least Squares")[
  A *linear predictor* finds coefficients $a_1 dots a_p$ that minimise the mean squared
  residual $E[e_n^2]$ (the average of the squared error, the spread idea from Chapter 10).
  Setting the derivative with respect to each coefficient to zero (the slope-is-zero
  condition for a minimum, from Chapter 11) leads to the *Yule-Walker equations*:

  $ R bold(a) = bold(r) $

  where $R$ is the $p times p$ autocorrelation matrix with entries $R_(i j) = E[x_n
  x_(n-|i-j|)]$ (a number that measures how much a sample resembles one $|i-j|$ steps
  away), and $bold(r)$ is the vector of autocorrelations $[R(1), R(2), dots,
  R(p)]$. Solving this system gives the *least-squares optimal* predictor coefficients. In
  practice the Levinson-Durbin algorithm (1947/1960) solves it in $O(p^2)$ rather than the
  $O(p^3)$ of general Gaussian elimination, by exploiting the Toeplitz (shift-invariant)
  structure of $R$: every diagonal of $R$ holds the same value.

  *Tiny example.* Suppose three consecutive samples are $[100, 108, 113]$.
  A first-order predictor uses $hat(x)_3 = a_1 times 108$. If we set $a_1 = 113/108
  approx 1.046$, the residual is zero for this pair. Over many samples the optimal $a_1$
  for slowly-changing audio is close to 1, because the previous sample is a good predictor of
  the next.
]

For audio, a predictor of order 4–32 typically suffices. FLAC uses up to order 32; mobile
speech codecs such as AMR use order 8–10 for narrowband or up to 16 for wideband. The
coefficients are computed on a short block (frame) of samples, typically 10–40 ms,
because audio statistics change slowly on that timescale but shift significantly over
longer spans.

=== The Residual's Distribution

The residuals of a well-tuned LPC predictor follow an approximately *Laplacian*
distribution: a sharp peak near zero, with tails that fall off exponentially. This is
different from a Gaussian bell curve (which falls off faster) or a uniform distribution
(which has flat tails). The Laplacian shape is important because it means most residuals
are small, but occasional large values occur. Rice and Golomb codes are designed precisely
for this shape.

#gomaths("Laplacian, Gaussian, and Uniform: Three Distribution Shapes")[
  A *distribution* (Chapter 10) just says how likely each value is. Three shapes recur
  throughout compression:
  - *Uniform*: every value in a range is equally likely. A flat line. A fair die is
    uniform. Hard to compress; nothing to predict.
  - *Gaussian* (the "bell curve"): values cluster around an average, and the probability
    drops off as $e^(-x^2)$, very fast, so extreme values are rare.
  - *Laplacian* (a "two-sided exponential"): also peaked at zero, but it drops off only as
    $e^(-abs(x))$. That slower decay produces a sharper central spike and fatter tails than
    a Gaussian: the typical value is tiny, yet the odd big spike is not shocking.

  *Why it matters here.* Prediction error in audio, images, and speech is almost always
  Laplacian-shaped: a flood of near-zero values with rare large ones. A Rice/Golomb code
  spends very few bits on the common small values and accepts a long codeword for the rare
  big ones, which is exactly the right trade for this shape. (It is the same shape JPEG's
  quantized DCT coefficients took in Chapter 42.)
]

#gomaths("Rice / Golomb Codes")[
  We built Golomb and Rice codes from scratch in Chapter 25 (Integer and Universal Codes)
  and used them again in Chapter 35 for BWT residuals. A *Golomb code* with parameter $M$
  encodes an integer $n >= 0$ as:
  - Quotient $q = floor(n \/ M)$ encoded in *unary* (that many 1-bits, then a 0).
  - Remainder $r = n mod M$ encoded in binary (using $ceil(log_2 M)$ bits).

  A *Rice code* is the special case $M = 2^k$ (a power of two), which makes the remainder
  just the last $k$ bits of $n$ (no division needed, only bit shifts). For signed residuals,
  map them to non-negative integers first: $0, 1, -1, 2, -2, dots$ (called zigzag or
  interleaving).

  *Why optimal for Laplacian?* For a geometric distribution (discrete analogue of
  exponential/Laplacian), the optimal entropy code length for value $n$ is approximately
  $n / M + log_2 M$ bits, which is exactly what a Golomb code gives. For each partition
  of samples, FLAC picks the $k$ that minimises total coded length. This is a one-dimensional
  search.
]

#mathrecall[Entropy from Chapter 18: $H = -sum_i p_i log_2 p_i$ bits per symbol. This is
the average surprise, and the lossless floor.]

=== Encoding and Decoding with LPC

Encoding is straightforward:
1. Divide the audio stream into *frames* (FLAC uses 4,096–65,536 samples).
2. Within each frame, choose a predictor order $p$ and solve for coefficients $a_1 dots a_p$.
3. Quantize the coefficients slightly (they must be stored in the file, costing bits).
4. Compute all residuals $e_n$.
5. Entropy-code the residuals with Rice codes.
6. Write coefficients + coded residuals to the bitstream.

Decoding reverses the process: decode the coefficients and residuals, then reconstruct
each sample from the predictor formula:

$ x_n = hat(x)_n + e_n = a_1 x_(n-1) + dots + a_p x_(n-p) + e_n $

Since the decoder reconstructs exactly the same sequence of integers, the process is
*perfectly lossless*: every bit of the original file is recovered.

#fig(
  [The lossless audio coding pipeline. PCM samples enter a frame splitter. Each frame
   goes through LPC analysis (producing coefficients) and residual computation. Rice coding
   compresses the residuals. The bitstream stores both coefficients and coded residuals.
   Decoding follows the exact reverse path.],
  cetz.canvas({
    import cetz.draw: *
    // Boxes
    rect((0,2),(2.5,3), name: "pcm")
    content("pcm", [PCM Samples])
    rect((3.5,2),(6,3), name: "lpc")
    content("lpc", [LPC Analysis])
    rect((7,2),(9.5,3), name: "rice")
    content("rice", [Rice Coder])
    rect((3.5,0),(6,1), name: "res")
    content("res", [Residuals])
    rect((7,0),(9.5,1), name: "bs")
    content("bs", [Bitstream])
    // Arrows
    line("pcm.east", "lpc.west", mark: (end: ">"))
    line("lpc.east", "rice.west", mark: (end: ">"))
    line("lpc.south", "res.north", mark: (end: ">"))
    content((4.75, 1.5), text(size: 8pt)[$e_n$])
    line("res.east", "bs.west", mark: (end: ">"))
    line("rice.south", "bs.north", mark: (end: ">"))
    content((3, 2.5), text(size: 8pt)[coeffs])
  })
)

== FLAC: the Open Standard

*FLAC* (Free Lossless Audio Codec) is the dominant lossless audio format. It was
created by *Josh Coalson* and first released on January 15, 2001. In January 2003, it was
adopted under the Xiph.Org Foundation umbrella. In December 2024, after years of work by
the IETF CELLAR working group, FLAC was formally specified as *RFC 9639*, giving it the
same rigorous standards-track status as HTTP or TLS.

The licence is intentionally permissive: the format specification and reference software
are under a BSD licence, and there are no patents to license. This matters enormously.
The entire lossless audio ecosystem could adopt FLAC without legal risk, and hardware
manufacturers (portable players, network streamers, smartphones) could implement it
freely. Today FLAC is the default lossless format for music distribution on Bandcamp,
Qobuz, and numerous archival services.

=== How FLAC Works

FLAC divides the audio into *blocks* (also called frames) of 4,096 to 65,536 samples.
Within each block it applies one of several predictor types:

- *Verbatim*: no prediction; store raw samples (used for the first few frames, or when
  prediction would not help).
- *Constant*: all samples are the same value; store just one number.
- *Fixed prediction*: one of four simple polynomial predictors (order 0–3) computed
  without any analysis, requiring no per-frame coefficient storage.
- *LPC prediction*: full least-squares LPC up to order 32, with quantized coefficients
  stored in the frame header.

FLAC chooses whichever predictor yields the smallest total cost (coefficients +
Rice-coded residuals). For most music, order-6 to order-12 LPC wins. The Rice parameter
$k$ is optimized per partition of residuals within each frame.

FLAC also stores MD5 checksums of the audio data so corruption can be detected, and it
embeds *seektable* markers so players can jump to a time offset without decoding from the
start. The container supports arbitrary metadata (cover art, lyrics, replay-gain tags).

#algo(
  name: "FLAC",
  year: "2001 (RFC 9639: 2024)",
  authors: "Josh Coalson; Xiph.Org Foundation",
  aim: "Bit-perfect lossless compression of PCM audio for archival and distribution.",
  complexity: "Encode O(N·p²) with Levinson-Durbin; decode O(N·p), both fast in practice.",
  strengths: "Royalty-free, open standard (RFC 9639); universal hardware support; fast decoding; seekable; checksummed; typical 40–60 % size reduction.",
  weaknesses: "Cannot reach the compression ratios of Monkey's Audio at max settings; not suitable for streaming without seektable; higher encoder CPU than fixed-predictor alternatives.",
  superseded: "Not superseded; remains the dominant open lossless format as of 2026.",
)[
  FLAC's fixed-predictor mode is a brilliant engineering compromise: store no coefficients
  at all, predict with simple differences ($x_n - x_(n-1)$, or second-differences), and
  rely on the Rice coder. This makes the encoder extremely fast and the decoder trivially
  simple, and that suits hardware with limited CPU.
]

=== Worked Example: Encoding a Ramp

Suppose four samples are: $[1000, 1004, 1009, 1015]$. Using the first-order fixed
predictor (predict = previous sample):
- Predictions: $[-, 1000, 1004, 1009]$
- Residuals: $[1000, 4, 5, 6]$ (the first sample is always stored verbatim)

With a Rice parameter $k=3$ (so $M=8$):
- $1000 / 8 = 125$ remainder $0$: unary 125 ones + zero = 126 bits. (Clearly a bad
  choice for the first sample; FLAC would use verbatim for it.)
- $4 / 8 = 0$ remainder $4$: unary 0 ones + zero + binary $100$ = 4 bits.
- $5 / 8 = 0$ remainder $5$: 4 bits.
- $6 / 8 = 0$ remainder $6$: 4 bits.

After the verbatim first sample, three residuals that each cost 4 bits instead of 16 bits
(raw PCM): a 4× saving on those samples. The LPC predictor made the data compressible.

#gopython("Simulating FLAC's Fixed Predictor in Python")[
  This snippet computes first-order residuals and zigzag-encodes them for Rice coding.

  ```python
  def fixed_predict_order1(samples: list[int]) -> list[int]:
      """First-order fixed predictor: residual[n] = x[n] - x[n-1]."""
      residuals = [samples[0]]  # store first sample verbatim
      for i in range(1, len(samples)):
          residuals.append(samples[i] - samples[i - 1])
      return residuals

  def zigzag(n: int) -> int:
      """Map signed int to non-negative: 0,1,-1,2,-2,... -> 0,1,2,3,4,..."""
      return (2 * n) if n >= 0 else (-2 * n - 1)

  def rice_length(value: int, k: int) -> int:
      """Number of bits to encode non-negative value with Rice(k)."""
      q = value >> k   # quotient
      return q + 1 + k  # unary(q) + separator + k remainder bits

  samples = [1000, 1004, 1009, 1015]
  residuals = fixed_predict_order1(samples)
  print("Residuals:", residuals)  # [1000, 4, 5, 6]

  # Find the best Rice k for residuals[1:] (skip verbatim first sample)
  tail = [zigzag(r) for r in residuals[1:]]
  best_k = min(range(0, 8), key=lambda k: sum(rice_length(v, k) for v in tail))
  total_bits = sum(rice_length(v, best_k) for v in tail)
  print(f"Best k={best_k}, total bits for tail: {total_bits}")
  # Best k=3, total bits for tail: 15  (vs 48 raw bits for 3 × 16-bit samples)
  ```

  Run this and confirm you get `Residuals: [1000, 4, 5, 6]` and `Best k=3` with 15 bits.
  (Because `zigzag` doubles each value, the residuals `4, 5, 6` become `8, 10, 12`, so the
  best Rice parameter lands at `k=3`, not `k=2`.) That is 15 bits to carry three samples
  that would otherwise need 48, which is roughly a 3× saving on this tiny ramp. The `>>` in
  `value >> k` is a bit-shift: `value >> k` is the same as `value // (2**k)`, but faster.
]

=== FLAC in Numbers

For a typical CD-quality stereo music file (44.1 kHz, 16-bit, stereo):
- Pop/rock: ~55 % of raw size (45 % reduction).
- Classical orchestral: ~58 % of raw size (42 % reduction).
- Speech (voice-only track): ~45 % of raw size (55 % reduction).
- Silence/near-silence: ~3 % of raw size (97 % reduction, using the constant predictor).

These are typical values; the actual result depends heavily on the content.

== ALAC: Apple's Lossless Codec

*ALAC* (Apple Lossless Audio Codec) was introduced by Apple on April 28, 2004, alongside
QuickTime 6.5.1, and was baked into iTunes 4.5. For seven years it was proprietary and
undocumented. Apple never published a format spec, and adoption outside Apple
hardware was limited. On *October 27, 2011*, Apple released the complete source code and
format specification under the *Apache License 2.0*, making ALAC royalty-free.

The 2011 open-source release was partly forced by practicality: the codec had already
been reverse-engineered. In March 2005, David Hammerton published a clean-room ALAC
decoder written in C, based purely on reverse engineering. It was technically impressive and
made proprietary obscurity increasingly pointless.

Technically, ALAC is close to FLAC in its approach: per-frame LPC analysis, residual
coding. The key difference is the *container*: ALAC wraps its compressed frames inside
the *MP4 container* (also called M4A when audio-only), using the ISO base media file
format. This was deliberate: MP4 was already the standard container for iTunes. It
meant that ALAC files could be embedded in the same infrastructure as AAC files, using
the same metadata, artwork, and chapter-marker features. The tradeoff is that MP4 adds
overhead and is somewhat less seekable than FLAC's native container.

ALAC is the lossless format of choice for Apple Music's lossless tier (launched June
2021). As of 2026, Apple Music streams ALAC at 16-bit/44.1 kHz (CD-quality) and up to
24-bit/192 kHz (high-resolution), delivered to iPhones, iPads, and Macs natively.

#algo(
  name: "ALAC (Apple Lossless Audio Codec)",
  year: "2004 (open source: 2011)",
  authors: "Apple Inc.",
  aim: "Bit-perfect lossless compression of PCM audio, natively embedded in MP4/M4A containers for the Apple ecosystem.",
  complexity: "Similar to FLAC; LPC order up to 30; Rice coding of residuals.",
  strengths: "Native MP4 container (familiar tooling, metadata richness); open source since 2011; supported natively on all Apple devices; comparable compression to FLAC.",
  weaknesses: "Slightly worse compression than FLAC on average; MP4 container adds overhead and parser complexity; less universal hardware support than FLAC outside Apple ecosystem.",
  superseded: "Not superseded within Apple's ecosystem.",
)[]

== WavPack: the Hybrid Codec

*WavPack* was created by *David Bryant* and first released in mid-1998, predating FLAC
by three years. As of 2025, version 5.8 is current, with multicore encoding, WebAssembly
decoding, and support for DSD (Direct Stream Digital) audio used in SACD discs.

WavPack's signature feature, found in no other lossless codec, is its *hybrid mode*. In
hybrid mode the encoder creates _two_ output files:

- A `.wv` file: a lossy-but-high-quality compressed stream at a user-specified bitrate
  (e.g. 256 kbps). This file sounds excellent and is much smaller than lossless.
- A `.wvc` "correction" file: the exact residual needed to reconstruct the original
  losslessly. This file is typically 100–200 kbps.

When only the `.wv` file is available (e.g. streamed over a slow connection), you get
lossy playback. When both are combined, you get perfect lossless reconstruction. This
This two-tier design was ahead of its time: a form of scalable coding that the broadcast
world spent years trying to engineer into more complex codecs.

#aside[
  WavPack is one of the few audio codecs to natively handle *32-bit floating-point PCM*,
  the native format of professional digital-audio-workstation (DAW) projects. While FLAC
  supports 32-bit integer, FLAC's predictor is not designed for floats and achieves poor
  compression. WavPack uses a separate floating-point coding path that preserves all
  mantissa and exponent bits losslessly.
]

== Monkey's Audio: Maximum Compression at a Cost

*Monkey's Audio*, created by *Matthew T. Ashland* and first released in 2000, chases the
highest possible compression ratio above all other goals. Its file extension is `.ape`.
At the "Insane" compression level, APE files are typically 5–8 % smaller than FLAC at
its maximum setting, a meaningful margin when storing thousands of albums.

The price is computational cost. APE's decoder is significantly more complex than FLAC's.
At high compression levels, the codec uses high-order predictors and a more expensive
entropy coder. Many embedded players (portable music players, car stereos) struggle with
the CPU load of decoding APE at maximum settings. Early iPod models refused to play APE
at all. FLAC's decoder, by contrast, was designed to run in real time on hardware from
the early 2000s.

Monkey's Audio remains popular in certain audiophile communities, particularly in China
where `.ape` files have historically circulated widely. But for most practical purposes
(hardware compatibility, streaming, long-term archival), FLAC has won.

#misconception[
  Monkey's Audio achieves much better compression than FLAC because it uses a fundamentally
  superior algorithm.
][
  The compression gap is real but modest (5–8 % at the extremes). The difference is that
  APE uses higher-order, more expensive models. FLAC's designers deliberately capped
  complexity to ensure fast real-time decoding on constrained hardware. "Better" depends
  on your goal: if decode speed matters, FLAC is better; if file size is everything and
  CPU is free, APE is better.
]

#scoreboard(
  caption: "Lossless audio codecs on a 4-minute CD-quality stereo track (raw = 42 MB)",
  [Technique], [Size], [Ratio], [Notes],
  [Raw 16-bit PCM], [42.0 MB], [1.0×], [Baseline],
  [FLAC (default)], [23.3 MB], [1.80×], [Open standard, universal hardware],
  [FLAC (max)], [21.8 MB], [1.93×], [Slower encode, same decode],
  [ALAC], [24.1 MB], [1.74×], [Apple MP4 container],
  [WavPack (lossless)], [23.1 MB], [1.82×], [Hybrid mode available],
  [Monkey's Audio (insane)], [20.2 MB], [2.08×], [Slow decode; APE format],
)

== Speech Coding: a Different Philosophy

Everything above stays strictly lossless. Speech codecs take the opposite extreme. A
phone call over 4G (AMR-WB) might use 12.65 kbps, compared to CD audio's 1,411 kbps.
That is a compression ratio of over 100:1. No perceptual codec designed for music comes
close to this.

How? By not compressing audio at all. Instead, speech codecs compress a *model of the
vocal tract* and a description of *what was said into it*.

=== The Vocoder Idea

The *vocoder* (voice coder) is the conceptual grandparent of all speech codecs. It was
invented by *Homer Dudley* at Bell Laboratories in 1936 and publicly demonstrated at
the New York World's Fair in 1939, where it ran on physical electrical circuits and
delighted audiences by making a machine "speak."

The key insight is this: human speech is produced by a two-part process. The *source* is
either a buzzing (voiced sounds like vowels, where the vocal cords vibrate with a
measurable pitch) or broadband noise (unvoiced sounds like "s" or "f"). The *filter* is
the vocal tract (the throat, mouth, and nose), which acts as a resonating tube that
shapes the source into the characteristic sounds of vowels and consonants.

#definition("Vocoder")[
  A vocoder encodes speech by transmitting *filter parameters* (how the vocal tract is
  shaped) and *source parameters* (voiced/unvoiced, pitch frequency, loudness) separately.
  The decoder reconstructs the speech by running the source signal through a filter with
  the received parameters. The waveform at the decoder is entirely synthesized; it is not
  a recording of the original.
]

This model is powerful because the _amount_ of information in the filter and source
parameters is far smaller than the information in the waveform. A vocal-tract filter can
be described by 10–16 numbers per 20 ms frame. A pitch period (for voiced speech) is a
single number. A voiced/unvoiced flag is one bit. The resulting bitrate is staggeringly
low. The synthesized speech sounds robotic, though, because the model does not capture all
the fine detail of the original waveform.

=== LPC-10: the Government Vocoder

The first widely deployed LPC codec was *LPC-10*, standardized by the US Department of
Defense as Federal Standard 1015 (FS-1015) and NATO STANAG 4198. It runs at exactly
2,400 bits per second (about 1.7 % of the bandwidth of a telephone-quality audio stream).
The first real-time 2,400 bps LPC implementation was demonstrated at MIT Lincoln
Laboratory in 1973.

LPC-10 analyzes each 22.5 ms frame of speech. For each frame it transmits:
- LPC coefficients (order 10): describing the vocal tract filter.
- Voiced/Unvoiced (V/UV) flag: one bit.
- Pitch period (for voiced frames): integer in samples.
- Gain: overall amplitude.

At 2,400 bps, the quality is distinctly "synthetic": intelligible but clearly artificial.
Military communications accepted this because 2,400 bps could be encrypted and transmitted
over secure satellite links that full telephone audio could not use. LPC-10 remained in
use until superseded by MELP (Mixed-Excitation Linear Prediction) in 1997.

=== CELP: Code-Excited Linear Prediction

The breakthrough that made speech codecs practical for commercial telephony was
*CELP*, proposed by *Manfred R. Schroeder* and *Bishnu S. Atal* of Bell Labs in their
landmark 1985 IEEE ICASSP paper.

The problem with LPC-10 was the source model. Using only voiced/unvoiced flags and a
single pitch estimate loses too much of the richness of real speech, and the result sounds
robotic. Schroeder and Atal's insight: instead of a simplified source model, use a
*codebook* of possible excitation signals, and transmit the index of whichever entry best
explains the current residual. The codebook entry, scaled by a gain, _is_ the excitation
signal for that frame.

The name reflects this: *Code-Excited* Linear Prediction. The excitation is determined by
a codebook index (a "code"), not a simple voiced/unvoiced rule.

#algo(
  name: "CELP (Code-Excited Linear Prediction)",
  year: "1985 (ICASSP paper); standardized in various forms 1988–1996",
  authors: "Manfred R. Schroeder, Bishnu S. Atal (Bell Laboratories)",
  aim: "Speech compression at 4.8–16 kbps with natural-sounding quality by using a codebook to represent the excitation signal.",
  complexity: "Analysis-by-synthesis: encoder searches the codebook exhaustively, O(N·C) per subframe, where C = codebook size. Decoder O(N·p).",
  strengths: "Far more natural than LPC vocoders; flexible bitrate; became the basis for nearly all modern speech codecs.",
  weaknesses: "Computationally very expensive at the encoder (codebook search); original CELP required a Cray-1 supercomputer for real-time operation.",
  superseded: "ACELP variants (AMR, G.723.1, G.729); EVS; neural codecs (LPCNet, Lyra).",
)[
  Schroeder and Atal's original 1983 simulations required 150 seconds of Cray-1 time to
  encode 1 second of speech. Within a decade, clever algebraic tricks and Moore's Law
  made it fit on a chip. The path from "requires a supercomputer" to
  "runs on a dumb 2G handset" is one of the most dramatic engineering compressions in the
  field.
]

=== How CELP Works: Analysis by Synthesis

CELP's encoder uses a technique called *analysis by synthesis*. Rather than analyzing
the input directly (as LPC-10 does), it tries different candidate excitation signals,
synthesizes the speech each would produce using the LPC filter, and picks the one closest
to the original. The loop works like this:

1. For each 5–20 ms subframe of input speech:
   a. Compute current LPC coefficients for the vocal-tract filter.
   b. Search through the codebook for the entry $c_i$ such that the synthesized signal
      $hat(x) = H c_i$ (where $H$ is the LPC synthesis filter) minimizes a perceptually
      weighted error criterion (not plain mean squared error, but weighted to emphasize
      formant regions).
   c. Transmit the index $i$ and the gain.
2. The decoder reconstructs speech by filtering the codebook entry through the LPC filter.

The *perceptual weighting filter* is the key innovation: it weights the error in the
frequency domain so that noise is allowed to be larger where the signal is louder (at
formants), and must be smaller in the quiet between-formant regions. This mimics masking.
The result is that the quality of CELP speech far exceeds what a raw MSE criterion would
suggest.

CELP also introduced a second codebook, the *adaptive codebook*, containing previous
excitation vectors. This handles the *long-term periodicity* of voiced speech (the pitch
pulse repeats every pitch period). The adaptive codebook search finds the best "pitch
lag" and gain, and the fixed codebook refines the residual. Two-stage codebook + LPC
filter is the architecture all modern speech codecs inherit.

=== ACELP: Making CELP Run on a Phone

The original CELP fixed codebook has thousands of entries, and searching it exhaustively
is too slow for real-time use on hardware of the 1990s. *Algebraic CELP (ACELP)* solves
this by replacing the arbitrary stored codebook with an *algebraically structured*
codebook.

In an algebraic codebook, each entry is specified not by storing a whole vector but by
specifying a small number of pulse positions and signs. For example, "two pulses: one
positive pulse at position 3, one negative pulse at position 17" generates one codebook
vector. Because the structure is purely positional, the search can be decomposed. Instead
of testing $2^13 = 8\,192$ entries, you search pulse positions independently, collapsing
the search from exponential to polynomial.

#definition("Algebraic Codebook")[
  An algebraic codebook represents each excitation vector as a sparse combination of unit
  pulses placed at specific positions. The "code" transmitted is a set of pulse positions
  and their signs, not an index into a stored table. This reduces codebook storage from
  many kilobytes to a compact description, and allows the search algorithm to decompose
  into fast sequential sub-searches.
]

ACELP was introduced in the mid-1990s and became the workhorse of digital telephony. The
*G.729* codec (8 kbps, 1996) and *G.723.1* (5.3/6.3 kbps, 1995) standardized ACELP for
the public telephone network. Then came the mobile world.

#algo(
  name: "ACELP (Algebraic Code-Excited Linear Prediction)",
  year: "1995–1996 (G.729, G.723.1); continuously refined through AMR and EVS",
  authors: "Multiple contributors; key work at Université de Sherbrooke (C. Laflamme, J.P. Adoul), France Télécom, Nokia, Ericsson, and others",
  aim: "Real-time speech compression at 4.75–23.85 kbps, suitable for embedded hardware; the standard algorithm for mobile telephony.",
  complexity: "Encode: O(N·P·S) where P = pulse count, S = subframe length; practically ~10 MIPS at 8 kbps. Decode: O(N·p).",
  strengths: "Dramatically lower computational cost than random CELP; high quality for speech; flexible bitrate; backbone of AMR, AMR-WB, EVS.",
  weaknesses: "Designed for speech, not music; degrades noticeably on background noise or music content at low bitrates.",
  superseded: "Neural vocoders (LPCNet, Lyra v2) at very low rates; EVS at high rates for music content.",
)[]

== AMR: the Adaptive Multirate Codec

*AMR-NB* (Adaptive Multi-Rate Narrowband) was adopted by 3GPP in 1998 and became the
standard speech codec for GSM and UMTS (3G) mobile networks worldwide. Its defining
feature is its *multirate* design: it can switch between *eight* bitrate modes (4.75,
5.15, 5.90, 6.70, 7.40, 7.95, 10.2, 12.2 kbps) in real time, choosing the rate that
fits current radio conditions. When the channel is good, it uses 12.2 kbps for maximum
quality. When interference increases, it drops to 4.75 kbps to maintain the connection:
intelligible low-quality speech is better than dropped calls.

AMR-NB covers narrowband speech: 300–3,400 Hz, the classic telephone frequency range.

*AMR-WB* (Adaptive Multi-Rate Wideband), also known as *G.722.2*, was selected by 3GPP
in December 2000 and standardized in January 2002. It extends the audio bandwidth to
50–7,000 Hz, a substantial improvement in naturalness and speaker recognition. The
difference between narrowband and wideband is immediately audible: narrowband speech
sounds "telephone-y," while wideband sounds close to face-to-face conversation. AMR-WB
supports nine modes ranging from 6.60 to 23.85 kbps.

Both AMR-NB and AMR-WB use ACELP under the hood.

#fig(
  [AMR bitrate adaptation. As the radio channel quality (C/I ratio) drops, the codec
   shifts to a lower bitrate mode to maintain connectivity. When conditions improve,
   it upgrades. The overall audio quality tracks channel quality rather than dropping
   to zero.],
  cetz.canvas({
    import cetz.draw: *
    // Time axis
    line((0,0), (9,0), mark: (end: ">"))
    content((9.3, 0), [time])
    // Quality axis
    line((0,0), (0,4), mark: (end: ">"))
    content((-0.9, 3.5), text(size: 8pt)[quality])
    // Channel quality curve (dashed)
    bezier((0,3), (3,3.5), (5,1.5), (9,2.5), stroke: (dash: "dashed"))
    content((9.4, 2.5), text(size: 7pt)[channel])
    // AMR rate steps
    line((0,3),(2,3), stroke: rgb("#0b5394") + 2pt)
    content((1, 3.25), text(size: 7pt)[12.2 k])
    line((2,2.8),(4,2.8), stroke: rgb("#0b5394") + 2pt)
    content((3, 3.05), text(size: 7pt)[10.2 k])
    line((4,1.5),(6,1.5), stroke: rgb("#0b5394") + 2pt)
    content((5, 1.75), text(size: 7pt)[5.9 k])
    line((6,2),(9,2), stroke: rgb("#0b5394") + 2pt)
    content((7.5, 2.25), text(size: 7pt)[7.4 k])
    // Labels
    content((0.3, -0.3), text(size: 7pt)[good])
    content((4.5, -0.3), text(size: 7pt)[noisy])
    content((7.5, -0.3), text(size: 7pt)[recovering])
  })
)

=== Why AMR Changed the World

Before AMR, mobile phones used a single fixed codec: GSM-FR (Full Rate) at 13 kbps.
Quality was fixed regardless of channel conditions. When the signal weakened, calls
dropped rather than gracefully degrading. AMR's rate-switching was a fundamental
architectural improvement: it turned a binary "connected/disconnected" into a continuous
quality spectrum. This is the same insight that drives adaptive bitrate (ABR) streaming
in video (Chapter 55): match your bitrate to what the channel can support.

#history[
  The AMR-WB codec algorithm was developed primarily at *Nokia Research Center* (Finland)
  and *Ericsson Research* (Sweden), submitted to 3GPP as the "VOICEAGE" candidate in
  1999–2000. Its inventor, *Vilmos Varsa* (Nokia), along with Ericsson's team, won the
  3GPP selection in December 2000. AMR-WB is now also ITU-T G.722.2, the first time
  the same codec held both a 3GPP standard number and an ITU-T recommendation. This reflected
  the global unification of telephony standards in the 2000s.
]

== EVS: Enhanced Voice Services

By the mid-2010s, mobile networks were transitioning from circuit-switched voice (2G/3G)
to *VoLTE* (Voice over LTE), which carries voice as IP packets over 4G. This created both an
opportunity and a need for a better codec. EVS is the result.

*EVS* (Enhanced Voice Services) was standardized by 3GPP in December 2014 as Release 12
(TS 26.441–26.448). It is a major step beyond AMR-WB in several respects:

- *Bandwidth*: EVS supports narrowband (up to 4 kHz), wideband (up to 8 kHz), super-wideband
  (up to 14 kHz), and full-band (up to 20 kHz) audio. Full-band covers the entire audible
  range of typical speech, plus music.
- *Bitrates*: 5.9 to 128 kbps across all modes. At the low end, EVS is a speech-only codec;
  at the high end (64–128 kbps full-band), it delivers near-transparent quality for music.
- *Mixed content*: At higher bitrates EVS uses an MDCT-based coding layer for music and
  background audio, alongside ACELP for speech. It switches between them frame by frame.
- *AMR-WB compatibility*: EVS includes an AMR-WB-compatible interoperability mode so
  calls can hand off between EVS and AMR-WB networks without disruption.
- *Error concealment*: Designed for LTE packet loss, with sophisticated packet loss
  concealment algorithms.

#algo(
  name: "EVS (Enhanced Voice Services)",
  year: "2014 (3GPP Release 12)",
  authors: "3GPP consortium (Ericsson, Nokia, Huawei, Qualcomm, France Télécom/Orange, and many others)",
  aim: "HD voice/audio codec for VoLTE and beyond: speech, music, and mixed content at 5.9–128 kbps, NB through full-band.",
  complexity: "ACELP path similar to AMR-WB; MDCT path similar to AAC at higher rates; combined mode adds switching overhead.",
  strengths: "Transparent speech quality at 24.4 kbps SWB; handles music gracefully; AMR-WB compatible; state-of-the-art error concealment; designed for IP networks.",
  weaknesses: "Complex implementation; not universally deployed (many carriers still use AMR-WB as of 2026); no open-source reference implementation comparable to Opus.",
  superseded: "Not superseded; EVS is the current 3GPP voice standard for 5G NR (VoNR).",
)[]

EVS is the codec behind HD Voice calls on modern smartphones when both devices are on VoLTE/VoNR networks with EVS support. The quality difference versus a 2G call is striking: the wider bandwidth makes voices sound present and natural rather than filtered and distant.

=== From AMR to EVS: A Family Tree

#fig(
  [The speech codec family tree. Each generation improved quality and bitrate flexibility
   while keeping the core ACELP architecture. Neural codecs (LPCNet, Lyra) represent a
   parallel branch beginning in 2019.],
  cetz.canvas({
    import cetz.draw: *
    // Root
    rect((3,8),(6.5,8.8), fill: rgb("#e8f0fe"), stroke: rgb("#0b5394"))
    content((4.75, 8.4), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[Vocoder (Dudley, 1936)])))
    // LPC-10
    rect((3,6.5),(6.5,7.3), fill: rgb("#e8f0fe"), stroke: rgb("#0b5394"))
    content((4.75, 6.9), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[LPC-10 (2400 bps, 1973)])))
    line((4.75,8),(4.75,7.3), mark: (end: ">"))
    // CELP
    rect((3,5),(6.5,5.8), fill: rgb("#d0e8d0"), stroke: rgb("#0b6e4f"))
    content((4.75, 5.4), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[CELP (Schroeder/Atal, 1985)])))
    line((4.75,6.5),(4.75,5.8), mark: (end: ">"))
    // ACELP
    rect((3,3.5),(6.5,4.3), fill: rgb("#d0e8d0"), stroke: rgb("#0b6e4f"))
    content((4.75, 3.9), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[ACELP / G.729 (1996)])))
    line((4.75,5),(4.75,4.3), mark: (end: ">"))
    // AMR
    rect((1,2),(4.5,2.8), fill: rgb("#fff3cd"), stroke: rgb("#c7851a"))
    content((2.75, 2.4), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[AMR-NB (1998)])))
    rect((5,2),(8.5,2.8), fill: rgb("#fff3cd"), stroke: rgb("#c7851a"))
    content((6.75, 2.4), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[AMR-WB (2002)])))
    line((4.75,3.5),(2.75,2.8), mark: (end: ">"))
    line((4.75,3.5),(6.75,2.8), mark: (end: ">"))
    // EVS
    rect((3,0.5),(6.5,1.3), fill: rgb("#fde8e8"), stroke: rgb("#9a2617"))
    content((4.75, 0.9), box(width: 3.1cm, inset: 2pt, align(center, text(size: 8pt)[EVS (3GPP, 2014)])))
    line((2.75,2),(4.75,1.3), mark: (end: ">"))
    line((6.75,2),(4.75,1.3), mark: (end: ">"))
  })
)

== Neural Speech Codecs: the Horizon

Chapter 49 introduced LPCNet as part of the Opus 1.5 discussion (Opus uses a neural
network for packet-loss concealment). It is worth pausing here to note why neural methods
attack _speech_ coding so naturally.

The source-filter model that underlies all CELP codecs is an approximation. It assumes
the vocal tract is a linear filter and the excitation is either periodic or noisy. But
real voices have subtle correlations, vibrato, breathiness, and hundreds of micro-textures
that algebraic codebooks miss. A neural network trained on thousands of hours of speech
can learn to predict these textures from the LPC residual, acting in effect as a learned
codebook far denser than any algebraic one.

*LPCNet* (Valin and Skoglund, 2019) hybridizes classic CELP and deep learning: the
decoder uses LPC coefficients (transmitted classically) plus a WaveRNN-style neural
network to synthesize the waveform sample-by-sample. At 1.6 kbps it produces speech
quality that beats CELP at much higher bitrates.

Google's *Lyra* (2021) and the subsequent *Lyra v2* (2022) take this further: at 3 kbps,
Lyra v2 (using a generative model called SoundStream's decoder) produces speech that
listeners prefer to AMR-WB at 9 kbps in blind tests.

These codecs will not fully replace CELP-based standards in the near future, since standards
processes are slow and neural decoders are power-hungry on cheap hardware. But they
demonstrate that the floor of intelligible speech quality at ultra-low bitrates is still
moving downward. We revisit the machine-learning machinery in Chapter 56, and neural audio
codecs as discrete tokenizers (SoundStream, EnCodec, DAC) get a full chapter of their own
in Chapter 60.

#checkpoint[
  A FLAC file for a 3-minute classical piano piece is 28 MB. The raw 16-bit 44.1 kHz
  stereo PCM would be about 47 MB. Approximately what compression ratio did FLAC achieve?
  Is this surprising given what you know about lossless compression?
][
  47 / 28 ≈ 1.68×, or about 40 % reduction. This is typical: piano has high spectral
  complexity and the LPC predictor cannot compress it as aggressively as, say, a quiet
  voice recording. Lossless music compression is bounded by the true entropy of musical
  audio, so the result is unsurprising.
]

#checkpoint[
  A CELP codec must search a codebook of 512 entries for each of 4 subframes per frame.
  Each codebook entry has 40 samples. How many multiply-accumulate operations (a
  multiply-accumulate, or MAC, is one "multiply two numbers and add to a running total,"
  the basic step of filtering) does one frame's codebook search require (ignoring the
  perceptual weighting filter)?
][
  512 entries × 4 subframes × 40 multiply-accumulates = 81,920 MACs per frame. At 50
  frames/second (20 ms frames), that is about 4 million MACs/second. This was achievable on a
  DSP of the late 1990s, though it required careful optimization.
]

== Putting It Together: Why These Two Families Coexist

It might seem that FLAC and CELP are solving completely different problems, but they share
a conceptual structure:

- Both use *linear prediction* to model temporal structure in the audio.
- Both transmit *residuals* (what the model got wrong).
- Both use *efficient codes* for those residuals (Rice for lossless, codebooks for speech).

The key difference is what happens next. FLAC transmits every residual bit exactly, with no
approximation. CELP quantizes the residual heavily (with a codebook), discards everything
the quantizer cannot represent, and reconstructs a _close approximation_ that
sounds good but is not the original waveform.

This is not a compromise in CELP's case: the decoder _synthesizes_ speech through the
LPC filter. The waveform it produces is not a degraded version of the original; it is a
synthesized speech signal that conveys the same linguistic content and much of the same
voice character. At low enough bitrates, this synthesis approach produces better-sounding
results than any waveform-preserving codec.

#keyidea[
  The difference between lossless and speech coding runs deeper than "perfect vs. imperfect
  reconstruction." It is a difference in _what is being compressed_: lossless codecs
  compress the *waveform*, while speech codecs compress a *model of how the waveform was
  produced*. Compressing the model is far more efficient, but only works when you know
  the model.
]

#gopython("Illustrating the Vocoder Concept: LPC Analysis in 20 Lines")[
  This simplified example computes LPC coefficients for a short speech-like signal using
  the autocorrelation method, the core step every speech codec performs every 20 ms.

  ```python
  import math

  def autocorr(signal: list[float], lag: int) -> float:
      """Compute autocorrelation of signal at given lag."""
      n = len(signal)
      total = 0.0
      for i in range(n - lag):
          total += signal[i] * signal[i + lag]
      return total

  def levinson(r: list[float]) -> list[float]:
      """Levinson-Durbin recursion: solve R*a = r for LPC coefficients.
      r[0] = autocorr at lag 0, r[1] at lag 1, etc.
      Returns coefficients a[1..p] (predictor weights)."""
      p = len(r) - 1
      a = [0.0] * (p + 1)
      err = r[0]
      for i in range(1, p + 1):
          # reflection coefficient k_i
          num = r[i] + sum(-a[j] * r[i - j] for j in range(1, i))
          k = num / err
          # update coefficients
          a_new = a[:]
          for j in range(1, i):
              a_new[j] = a[j] - k * a[i - j]
          a_new[i] = -k
          a = a_new
          err *= (1.0 - k * k)
      return a[1:]  # a[1..p]

  # Simulate a voiced speech frame: 160 samples of a 100 Hz sine at 8000 Hz sample rate
  N = 160
  freq = 100.0
  Fs = 8000.0
  samples = [math.sin(2 * math.pi * freq * n / Fs) for n in range(N)]

  order = 4
  r = [autocorr(samples, lag) for lag in range(order + 1)]
  coeffs = levinson(r)
  print("LPC coefficients (order 4):", [f"{c:.4f}" for c in coeffs])
  # For a pure sine wave, a 2nd-order predictor can predict it exactly.
  # At order 4 you will see most energy in the first two coefficients.
  ```

  *How to read this.* The `levinson` function implements the Yule-Walker solution in
  $O(p^2)$ operations. The output coefficients describe a filter that models the
  "vocal tract" of this signal. Every 20 ms, a speech codec runs exactly this on real
  speech and transmits the resulting 8–16 numbers instead of the 160 raw samples.
]

== A Note on Lossless Limits

We said FLAC achieves roughly 40–60 % reduction on music. But can we be more precise
about the ceiling?

Claude Shannon's source coding theorem (Chapter 19) says no lossless code can compress
below the entropy rate of the source. For audio, the "source" includes all the statistical
structure: within-frame correlations (which LPC exploits), across-frame correlations (which
some codecs partially exploit through long-term prediction), stereo correlation (joint
stereo coding, which FLAC supports via "mid-side" mode), and frequency-domain structure
(which FLAC does _not_ exploit, because doing so would complicate the predictor).

Modern research suggests the theoretical limit for lossless audio compression on typical
music is around 30–35 % of raw size, or about 2.9–3.3×. FLAC at default settings reaches
~1.8×; at maximum settings ~1.95×. So there is still a gap, but closing it would require
far more complex models.

Lossless codecs deliberately leave this gap open in exchange for fast decoding and
robustness. This is an engineering choice, not a failure of the math.

#history[
  The history of lossless audio is quieter than the patent wars around MP3 and AAC,
  because lossless codecs have generally avoided patents. Josh Coalson released FLAC under
  a BSD licence from day one, explicitly to prevent the kind of royalty disputes that had
  embroiled the lossy world. Apple's decision to open-source ALAC in 2011 (prompted partly
  by growing community pressure and the success of FLAC) was another signal that the
  industry recognized that patent-free lossless codecs benefit everyone: hardware makers,
  streaming services, and listeners alike. The December 2024 publication of RFC 9639 is
  the culmination. FLAC is now an IETF standard, as rigorous and permanent as the protocols
  underlying the internet itself.
]

#takeaways((
  [Lossless audio codecs (FLAC, ALAC, WavPack, Monkey's Audio) all use the same core engine: linear prediction to generate small residuals, plus Rice/Golomb entropy coding for those residuals. The differences are in predictor design, container format, and compression-vs-speed tradeoffs.],
  [FLAC is the open standard (RFC 9639, December 2024), released by Josh Coalson in 2001 under a BSD licence, with universal hardware support and ~40–60 % size reduction on music.],
  [ALAC lives in the Apple MP4 ecosystem; WavPack's hybrid mode provides both a portable lossy file and a lossless correction file; Monkey's Audio squeezes 5–8 % more at the cost of far slower decoding.],
  [The lossless compression ceiling for music is approximately 1.8–2.1× for typical codecs, bounded by the true Shannon entropy of musical audio.],
  [Speech codecs take a completely different approach: model the vocal tract as a source (buzzing or noise) plus a resonant filter, and transmit model parameters instead of the waveform.],
  [LPC-10 (2,400 bps, 1973) was the first government-standard speech codec; CELP (Schroeder and Atal, Bell Labs, 1985) replaced its simplified source model with a codebook, dramatically improving naturalness.],
  [ACELP reduced CELP's codebook search from exponential to polynomial complexity by using algebraic (sparse pulse) codebooks, enabling real-time operation on mobile hardware.],
  [AMR-NB (1998) and AMR-WB (2002) brought adaptive bitrate switching to mobile voice; EVS (2014) added super-wideband and full-band support, and is the current standard for VoLTE and 5G NR.],
  [Neural vocoders such as LPCNet and Lyra now outperform classical CELP at ultra-low bitrates by learning the excitation distribution from data; Chapter 60 covers neural audio codecs in depth.],
))

== Exercises

#exercise("50.1", 1)[
  A lossless audio file is 31 MB; the original raw PCM (44.1 kHz, 16-bit, stereo, 3 min
  20 sec) would be how large? Compute the compression ratio FLAC achieved. Show your work.
]
#solution("50.1")[
  Raw size: 44,100 samples/s × 2 bytes/sample × 2 channels × 200 s = 35,280,000 bytes
  ≈ 33.7 MB. Ratio: 33.7 / 31 ≈ 1.09×. That is unusually poor, suggesting the audio
  has high complexity or contains significant high-frequency content (e.g. percussion).
]

#exercise("50.2", 1)[
  Explain in plain words why Rice codes are near-optimal for LPC residuals.
  What statistical property of the residuals makes them a good fit?
]
#solution("50.2")[
  LPC residuals follow an approximately Laplacian (two-sided exponential) distribution:
  most values cluster near zero, with the probability of value $n$ proportional to
  $lambda^(|n|)$ for some $lambda < 1$. Rice codes are optimal for geometric distributions,
  which are the discrete analogue of the exponential. By choosing the Rice parameter $k$
  to match the typical magnitude of residuals in each block, the coder assigns short
  codes to common small values and longer codes to rare large values, matching the
  distribution and approaching the entropy limit.
]

#exercise("50.3", 2)[
  Write a Python function `rice_encode(values: list[int], k: int) -> list[int]` that
  takes a list of signed integers and returns a list of bit counts (the total bits needed
  to Rice-encode each value, using the zigzag mapping for negatives). Compute the total
  bits for `values = [0, 1, -1, 3, -5, 10]` at `k = 2` and at `k = 3`. Which k is
  better?
]
#solution("50.3")[
  ```python
  def zigzag(n: int) -> int:
      return 2 * n if n >= 0 else -2 * n - 1

  def rice_bits(values: list[int], k: int) -> int:
      total = 0
      for v in values:
          u = zigzag(v)
          q = u >> k
          total += q + 1 + k  # unary(q) + stop bit + k remainder bits
      return total

  vals = [0, 1, -1, 3, -5, 10]
  print(rice_bits(vals, 2))  # k=2: total bits
  print(rice_bits(vals, 3))  # k=3: total bits
  ```
  k=2 gives: zigzag → [0,2,1,6,9,20]; quotients $q = u >> 2$ are $[0,0,0,1,2,5]$; bits per
  value are $q+1+2$: (0+1+2)+(0+1+2)+(0+1+2)+(1+1+2)+(2+1+2)+(5+1+2) =
  3+3+3+4+5+8 = 26.
  k=3 gives: same zigzag; quotients $q = u >> 3$ are $[0,0,0,0,1,2]$; bits per value are
  $q+1+3$: (0+1+3)+(0+1+3)+(0+1+3)+(0+1+3)+(1+1+3)+(2+1+3) = 4+4+4+4+5+6 = 27.
  k=2 is better (26 < 27 bits) for this distribution of values.
]

#exercise("50.4", 2)[
  In CELP, the encoder must transmit the index into a fixed codebook of 1,024 entries
  for each subframe. Each frame (20 ms at 8 kHz = 160 samples) has 4 subframes.
  (a) How many bits per frame does just the fixed-codebook index cost?
  (b) The adaptive codebook (pitch) uses an integer lag from 20 to 143 samples;
  how many bits is that?
  (c) The LPC coefficients are quantized with 36 bits/frame. If each frame also has a gain
  parameter using 7 bits and a V/UV flag bit, what is the total bitrate at 50 frames/second?
]
#solution("50.4")[
  (a) $log_2(1024) = 10$ bits/subframe $times$ 4 subframes $= 40$ bits for fixed codebook
  indices. (b) Lag range $= 143 - 20 + 1 = 124$ values; $ceil(log_2 124) = 7$ bits.
  (c) Per frame: 36 (LPC) + 40 (fixed codebook) + 7 (adaptive codebook) + 7 (gain) +
  1 (V/UV) = 91 bits. At 50 frames/s: $91 times 50 = 4,550$ bps ≈ 4.5 kbps.
  Actual codecs add more bits for refined quantization and multiple subframe gains,
  reaching 5.9–8 kbps for narrow-band ACELP codecs.
]

#exercise("50.5", 2)[
  Compare FLAC and ALAC from a format-design perspective. Why did Apple choose to wrap
  ALAC inside an MP4 container? What is lost and what is gained by this choice?
]
#solution("50.5")[
  Apple chose MP4 because iTunes already used MP4/M4A for AAC, and sharing the container
  format means the same tools, libraries, metadata APIs, and hardware parsers work for
  both lossy (AAC) and lossless (ALAC) content. Users see one file type; hardware has
  one container parser to implement.
  Lost: slightly more container overhead; MP4 requires parsing atom structures not needed
  for FLAC's simpler bitstream; random seeking requires the "moov" atom, which can be at
  the end of a file (a streaming problem).
  Gained: rich metadata (artwork, chapters, iTunes Store metadata); single-format
  ecosystem compatibility; unified library management in Apple software.
]

#exercise("50.6", 3)[
  Design a thought experiment. A phone call lasts 30 seconds. One side uses AMR-NB at
  12.2 kbps; the other uses FLAC. Both record the same person speaking in a quiet room.
  (a) Estimate the file sizes for each (raw PCM at 8 kHz, 16-bit, 1 channel for AMR-NB;
  44.1 kHz, 16-bit, 1 channel for FLAC). (b) Compute the effective compression ratio of
  each versus their respective PCMs. (c) Why is AMR-NB's ratio so much higher? Use the
  concepts of the chapter: source model, entropy of residuals, lossless ceiling.
]
#solution("50.6")[
  (a) AMR-NB: 12.2 kbps × 30 s / 8 = 45.75 kB compressed. Raw PCM: 8,000 × 2 × 30 =
  480,000 bytes = 468 kB. FLAC: raw 44,100 × 2 × 30 = 2,646,000 bytes ≈ 2.52 MB;
  FLAC for speech typically reaches ~45 % of raw ≈ 1.13 MB.
  (b) AMR-NB ratio: 468 / 45.75 ≈ 10.2×. FLAC ratio: 2,520 / 1,130 ≈ 2.2×.
  (c) AMR-NB compresses a _model_ (10 LPC coefficients + pitch + gain + codebook index
  per 20 ms frame), not the waveform. The total information per frame is ~100 bits
  regardless of how complex the speech is. FLAC must preserve every sample's exact value;
  the entropy of the speech residuals is still high even after LPC prediction, because
  every subtle phoneme detail must survive. AMR-NB discards all waveform detail below
  the level of the ACELP model's resolution; everything the model cannot represent is
  simply dropped. That is why it achieves 10× versus FLAC's 2×: AMR-NB is compressing
  _linguistic content_, not audio samples.
]

== Further Reading

- #link("https://www.rfc-editor.org/rfc/rfc9639.txt")[Coalson et al. (IETF CELLAR, 2024). _Free Lossless Audio Codec (FLAC)_. RFC 9639.] The formal IETF specification of FLAC, published December 2024.

- #link("https://xiph.org/flac/2024/12/19/rfc-9639-published.html")[Xiph.Org Foundation. _FLAC is now formally specified in RFC 9639_. December 2024.] The official announcement with context on the years-long CELLAR working group effort.

- #link("https://speechprocessingbook.aalto.fi/Transmission/Code-excited_linear_prediction_CELP.html")[Aalto University Speech Processing Textbook. _Code-Excited Linear Prediction (CELP)_.] A rigorous, freely accessible treatment of CELP with worked examples of the analysis-by-synthesis loop.

- #link("https://www.3gpp.org/news-events/3gpp-news/evs-news")[3GPP. _Enhanced Voice Services Codec for LTE_. 2014.] The official 3GPP announcement of EVS standardization, with architecture overview.

- #link("https://arxiv.org/abs/1810.11846")[Valin, J.-M. and Skoglund, J. (2019). _LPCNet: Improving Neural Speech Synthesis Through Linear Prediction_. arXiv:1810.11846.] The paper that showed classical LPC coefficients combined with a neural decoder can beat CELP at 1.6 kbps.

- #link("https://www.aes.org/e-lib/browse.cfm?elib=8079")[Brandenburg, K. (1999). _MP3 and AAC Explained_. AES 17th International Conference.] Karlheinz Brandenburg's own account of the development of MP3 and AAC, valuable context for how the perceptual coding paradigm was established.

- #link("https://en.wikipedia.org/wiki/WavPack")[WavPack Wikipedia article.] Covers the hybrid mode in detail and the evolution through version 5.x.

#bridge[
  We have now covered the full range of audio compression, from psychoacoustics and
  lossy perceptual codecs (Chapters 46–49) to lossless and speech coding (this chapter).
  Audio, however, is only half the story of the media pipeline that delivers most of the
  world's compressed bits. The vast majority of data flowing across the internet is _video_:
  moving images at 24–120 frames per second, each frame as complex as the JPEG images of
  Chapter 42, but with the added dimension of time. Chapter 51 introduces the idea that
  makes video compression possible at all: *motion compensation*. If two consecutive video
  frames are similar, we can describe the second frame as a slightly shifted version of the
  first, plus a small correction. The correction is far cheaper to code than a new frame.
  That is the insight behind every video codec from H.261 (1988) to AV1 (2018) to the
  learned neural video codecs of Chapter 59.
]
